// ABOUTME: AppFolio Reports API (V2) catalog. All 48 reports here have verified columns/filters,
// ABOUTME: sourced from AppFolio's own schema export, from CryptoCultCurt, or from live verification.
export interface ReportColumn {
  name: string;
  type: string;
}

export interface ReportDescriptor {
  id: string;
  title: string;
  summary: string;
  tags: string[];
  verified: boolean;
  source?: string;
  columns: ReportColumn[];
  filters: ReportColumn[];
  // Filters AppFolio accepts with HTTP 200 but does not apply, or whose value vocabulary is not
  // what its name suggests. describe_report returns this so a caller sees it before trusting a
  // filtered result. Only set where the behaviour was reproduced live against a real account.
  filterCaveats?: string;
}

// Attribution: every entry below carrying source "cryptocultcurt-v2 (ISC, attributed)" reuses its
// V2 column/filter names, with attribution under its ISC license, from
// https://github.com/CryptoCultCurt/appfolio-mcp-server, the only prior implementation verified
// against AppFolio's live V2 Reports API at design time. That covers vendor_directory plus the
// financial, vendor, leasing, property, tenant, and workflow reports added alongside it.
export const REPORTS: ReportDescriptor[] = [
  // vendor_directory's columns below are the full 32 the report actually returns, read off a live
  // POST /reports/vendor_directory against the Perpetual Realty account on 2026-08-27. The prior
  // list carried 8 of them, taken from third-party attribution rather than a live response, and
  // named no identity column at all, which is how a consumer came to read a "row.id" that has
  // never existed. epa_cert_expires, state_lic_expires, contract_expires, discount_adjustment and
  // markup_adjustment were null in all 301 live rows, so the three dates take their siblings'
  // type and the two adjustments are left unknown rather than guessed at. The filters below are
  // still the attributed ones. liability_expiration_to looked like it narrowed nothing at the time
  // this was written, but that was runReport's own bug (it wrapped every filter in a { filters }
  // envelope AppFolio silently ignores), not this report's: re-verified live after that fix,
  // liability_expiration_to correctly returns 291 rows for a 2022 cutoff and 301 for a 2099 one.
  {
    id: "vendor_directory",
    title: "Vendor Directory",
    summary: "All vendors with license/insurance expirations and compliance flags.",
    tags: ["vendors", "compliance"],
    verified: true,
    source: "live verification; filters from cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "company_name", type: "string" },
      { name: "name", type: "string" },
      { name: "address", type: "string" },
      { name: "street", type: "string" },
      { name: "street2", type: "string" },
      { name: "city", type: "string" },
      { name: "state", type: "string" },
      { name: "zip", type: "string" },
      { name: "phone_numbers", type: "string" },
      { name: "email", type: "string" },
      { name: "default_gl_account", type: "string" },
      { name: "payment_type", type: "string" },
      { name: "send1099", type: "string" },
      { name: "workers_comp_expires", type: "date" },
      { name: "liability_ins_expires", type: "date" },
      { name: "epa_cert_expires", type: "date" },
      { name: "auto_ins_expires", type: "date" },
      { name: "state_lic_expires", type: "date" },
      { name: "contract_expires", type: "date" },
      { name: "tags", type: "string" },
      { name: "vendor_id", type: "integer" },
      { name: "vendor_trades", type: "string" },
      { name: "do_not_use_for_work_order", type: "string" },
      { name: "terms", type: "string" },
      { name: "first_name", type: "string" },
      { name: "last_name", type: "string" },
      { name: "vendor_integration_id", type: "string" },
      { name: "created_by", type: "string" },
      { name: "vendor_type", type: "string" },
      { name: "portal_activated", type: "string" },
      { name: "discount_adjustment", type: "unknown" },
      { name: "markup_adjustment", type: "unknown" },
    ],
    filters: [
      { name: "liability_expiration_to", type: "date" },
      { name: "workers_comp_expiration_to", type: "date" },
      { name: "epa_expiration_to", type: "date" },
      { name: "auto_insurance_expiration_to", type: "date" },
      { name: "state_license_expiration_to", type: "date" },
      { name: "contract_expiration_to", type: "date" },
    ],
  },
  // rent_roll's V2 columns below are sourced from AppFolio's own Reports API OpenAPI schema
  // export, provided by the project owner (components.schemas.RentRollRequest/Response), not
  // browsed UI prose or a guess. See .superpowers/sdd/verified-report-columns.md. property_address
  // and property are additions on top of that export: the live response carries them (confirmed
  // against a real 230-row account, 2026-08-28) even though the schema export didn't mention them,
  // and rentRollSummary depends on both as the fallback for a property with no property_name.
  {
    id: "rent_roll",
    title: "Rent Roll",
    summary: "Occupancy and rent by unit.",
    tags: ["occupancy"],
    verified: true,
    source: "AppFolio Reports API OpenAPI schema export; property_address/property live-verified, 2026-08-28",
    columns: [
      { name: "property_id", type: "integer" },
      { name: "property_name", type: "string" },
      { name: "property_address", type: "string" },
      { name: "property", type: "string" },
      { name: "unit_id", type: "integer" },
      { name: "unit", type: "string" },
      { name: "sqft", type: "integer" },
      { name: "status", type: "string" },
      { name: "market_rent", type: "string" },
      { name: "rent", type: "string" },
      { name: "lease_to", type: "date" },
      { name: "tenant_id", type: "integer" },
      { name: "tenant", type: "string" },
    ],
    filters: [
      { name: "as_of_to", type: "date" },
      { name: "properties.properties_ids", type: "array" },
      { name: "unit_visibility", type: "string" },
      { name: "non_revenue_units", type: "string" },
    ],
  },
  // delinquency's V2 columns below are sourced from AppFolio's own Reports API OpenAPI schema
  // export, provided by the project owner (components.schemas.DelinquencyRequest/Response), not
  // browsed UI prose or a guess. See .superpowers/sdd/verified-report-columns.md. property_address
  // is an addition on top of that export: the live response carries it (confirmed against a real
  // account, 2026-08-28) even though the schema export didn't mention it, and delinquencyAging
  // depends on it as the label for a property with no property_name, which is common in practice.
  {
    id: "delinquency",
    title: "Delinquency",
    summary: "Aging balances by tenant.",
    tags: ["financial"],
    verified: true,
    source: "AppFolio Reports API OpenAPI schema export; property_address live-verified, 2026-08-28",
    columns: [
      { name: "property_id", type: "integer" },
      { name: "property_name", type: "string" },
      { name: "property_address", type: "string" },
      { name: "unit", type: "string" },
      { name: "unit_id", type: "integer" },
      { name: "occupancy_id", type: "integer" },
      { name: "name", type: "string" },
      { name: "tenant_status", type: "string" },
      { name: "00_to30", type: "string" },
      { name: "30_to60", type: "string" },
      { name: "60_to90", type: "string" },
      { name: "90_plus", type: "string" },
      { name: "in_collections", type: "string" },
      { name: "collections_agency", type: "string" },
      { name: "payment_plan", type: "string" },
      { name: "nsf", type: "integer" },
      { name: "late", type: "integer" },
      { name: "certified_funds_only", type: "string" },
    ],
    filters: [
      { name: "properties.properties_ids", type: "array" },
      { name: "tenant_statuses", type: "array" },
      { name: "amount_owed_in_account", type: "string" },
      { name: "balance_operator.amount", type: "string" },
      { name: "balance_operator.comparator", type: "string" },
    ],
  },
  // work_order's V2 columns below are sourced from AppFolio's own Reports API OpenAPI schema
  // export, provided by the project owner (components.schemas.WorkOrderRequest/Response), not
  // browsed UI prose or a guess. See .superpowers/sdd/verified-report-columns.md. property_address
  // and property are additions on top of that export: the live response carries them (confirmed
  // against a real account, 2026-08-28) even though the schema export didn't mention them, and
  // workOrderAging depends on both as the fallback for a property with no property_name.
  {
    id: "work_order",
    title: "Work Orders",
    summary: "Open and closed maintenance tickets.",
    tags: ["maintenance"],
    verified: true,
    source: "AppFolio Reports API OpenAPI schema export; property_address/property live-verified, 2026-08-28",
    columns: [
      { name: "work_order_id", type: "integer" },
      { name: "work_order_number", type: "string" },
      { name: "property_id", type: "integer" },
      { name: "property_name", type: "string" },
      { name: "property_address", type: "string" },
      { name: "property", type: "string" },
      { name: "vendor_id", type: "integer" },
      { name: "vendor", type: "string" },
      { name: "priority", type: "string" },
      { name: "status", type: "string" },
      { name: "created_at", type: "date" },
      { name: "scheduled_start", type: "date" },
      { name: "completed_on", type: "date" },
      { name: "estimate_req_on", type: "date" },
      { name: "estimated_on", type: "date" },
    ],
    filters: [
      { name: "property.*", type: "object" },
      { name: "work_order_statuses", type: "array" },
      { name: "priority", type: "string" },
      { name: "status_date_range_from", type: "date" },
      { name: "status_date_range_to", type: "date" },
    ],
    filterCaveats:
      "work_order_statuses takes numeric status ids, not status names. Verified live: 0 New, " +
      "1 Estimate Requested, 2 Estimated, 3 Scheduled, 4 Completed, 5 Canceled, 6 Waiting, " +
      "7 Completed No Need To Bill, 8 Work Done, 9 Assigned. A name string is not rejected, it " +
      "coerces to 0, so passing ['Completed'] silently returns the New work orders. Passing an " +
      "empty array returns every status (675 rows on the verifying account), while omitting the " +
      "filter returns only the open ones (41).",
  },
  {
    id: "account_totals",
    title: "Account Totals",
    summary: "Reserve, net, and ending balance per property over a posting date range.",
    tags: ["financial"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "property", type: "string" },
      { name: "property_name", type: "string" },
      { name: "property_id", type: "integer" },
      { name: "property_address", type: "string" },
      { name: "property_street", type: "string" },
      { name: "property_street2", type: "string" },
      { name: "property_city", type: "string" },
      { name: "property_state", type: "string" },
      { name: "property_zip", type: "string" },
      { name: "reserve_amount", type: "number" },
      { name: "net_amount", type: "number" },
      { name: "ending_balance", type: "number" },
    ],
    filters: [
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "gl_account_ids", type: "string" },
      { name: "posted_on_from", type: "date" },
      { name: "posted_on_to", type: "date" },
    ],
  },
  {
    id: "aged_payables_summary",
    title: "Aged Payables Summary",
    summary: "Payables owed per payee and property, bucketed by age.",
    tags: ["financial", "vendors"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "property", type: "string" },
      { name: "property_name", type: "string" },
      { name: "property_id", type: "integer" },
      { name: "property_address", type: "string" },
      { name: "property_street", type: "string" },
      { name: "property_street2", type: "string" },
      { name: "property_city", type: "string" },
      { name: "property_state", type: "string" },
      { name: "property_zip", type: "string" },
      { name: "payee_name", type: "string" },
      { name: "unit_id", type: "integer" },
      { name: "amount_payable", type: "number" },
      { name: "not_yet_due", type: "number" },
      { name: "0_to30", type: "number" },
      { name: "30_to60", type: "number" },
      { name: "60_to90", type: "number" },
      { name: "90_plus", type: "number" },
      { name: "30_plus", type: "number" },
      { name: "60_plus", type: "number" },
      { name: "party_id", type: "integer" },
      { name: "party_type", type: "string" },
    ],
    filters: [
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "occurred_on", type: "date" },
      { name: "party_contact_info.company_id", type: "integer" },
      { name: "balance_operator.amount", type: "number" },
      { name: "balance_operator.comparator", type: "string" },
    ],
  },
  {
    id: "aged_receivables_detail",
    title: "Aged Receivable Detail",
    summary: "Every open receivable line with its aging bucket and payer.",
    tags: ["financial", "tenants"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "payer_name", type: "string" },
      { name: "property", type: "string" },
      { name: "property_name", type: "string" },
      { name: "property_id", type: "integer" },
      { name: "property_address", type: "string" },
      { name: "property_street", type: "string" },
      { name: "property_street2", type: "string" },
      { name: "property_city", type: "string" },
      { name: "property_state", type: "string" },
      { name: "property_zip", type: "string" },
      { name: "invoice_occurred_on", type: "date" },
      { name: "account_number", type: "string" },
      { name: "account_name", type: "string" },
      { name: "account_id", type: "integer" },
      { name: "total_amount", type: "number" },
      { name: "amount_receivable", type: "number" },
      { name: "future_charges", type: "number" },
      { name: "0_to30", type: "number" },
      { name: "30_to60", type: "number" },
      { name: "60_to90", type: "number" },
      { name: "90_plus", type: "number" },
      { name: "30_plus", type: "number" },
      { name: "60_plus", type: "number" },
      { name: "occupancy_name", type: "string" },
      { name: "account", type: "string" },
      { name: "unit_address", type: "string" },
      { name: "unit_street", type: "string" },
      { name: "unit_street2", type: "string" },
      { name: "unit_city", type: "string" },
      { name: "unit_state", type: "string" },
      { name: "unit_zip", type: "string" },
      { name: "unit_name", type: "string" },
      { name: "unit_type", type: "string" },
      { name: "unit_tags", type: "array" },
      { name: "tenant_status", type: "string" },
      { name: "payment_plan", type: "string" },
      { name: "txn_id", type: "integer" },
      { name: "occupancy_id", type: "integer" },
      { name: "selected_tenant_id", type: "integer" },
      { name: "unit_id", type: "integer" },
    ],
    filters: [
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "tags", type: "array" },
      { name: "balance_operator.amount", type: "number" },
      { name: "balance_operator.comparator", type: "string" },
      { name: "tenant_statuses", type: "array" },
      { name: "occurred_on_to", type: "date" },
      { name: "gl_account_map_id", type: "integer" },
      { name: "as_of", type: "date" },
    ],
  },
  {
    id: "annual_budget_comparative",
    title: "Annual Budget - Comparative",
    summary: "Month to date and year to date actuals against budget, with variances.",
    tags: ["financial", "budget"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "account_name", type: "string" },
      { name: "mtd_actual", type: "number" },
      { name: "mtd_budget", type: "number" },
      { name: "mtd_amount_variance", type: "number" },
      { name: "mtd_percent_variance", type: "number" },
      { name: "ytd_actual", type: "number" },
      { name: "ytd_budget", type: "number" },
      { name: "ytd_amount_variance", type: "number" },
      { name: "ytd_percent_variance", type: "number" },
      { name: "annual", type: "number" },
      { name: "account_number", type: "string" },
      { name: "note", type: "string" },
      { name: "variance_note", type: "string" },
    ],
    filters: [
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "occurred_on_to", type: "date" },
      { name: "additional_account_types", type: "array" },
      { name: "gl_account_map_id", type: "integer" },
      { name: "level_of_detail", type: "string" },
      { name: "periods", type: "object" },
    ],
  },
  {
    id: "annual_budget_forecast",
    title: "Annual Budget - Forecast",
    summary: "Budgeted amounts per account across the months of a forecast period.",
    tags: ["financial", "budget"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "account_name", type: "string" },
      { name: "account_code", type: "string" },
      { name: "months", type: "array" },
      { name: "total", type: "number" },
      { name: "property_name", type: "string" },
      { name: "property_id", type: "integer" },
      { name: "account_id", type: "integer" },
      { name: "note", type: "string" },
    ],
    filters: [
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "period_from", type: "date" },
      { name: "period_to", type: "date" },
      { name: "consolidate", type: "string" },
      { name: "gl_account_map_id", type: "integer" },
    ],
  },
  {
    id: "balance_sheet",
    title: "Balance Sheet",
    summary: "Account balances as of a posting date.",
    tags: ["financial"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "account_name", type: "string" },
      { name: "balance", type: "number" },
      { name: "account_number", type: "string" },
    ],
    filters: [
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "posted_on_to", type: "date" },
      { name: "gl_account_map_id", type: "integer" },
      { name: "level_of_detail", type: "string" },
      { name: "include_zero_balance_gl_accounts", type: "string" },
    ],
  },
  {
    id: "budget_comparative",
    title: "Budget - Comparative",
    summary: "Actual and budget figures for a period next to a comparison period.",
    tags: ["financial", "budget"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "account_number", type: "string" },
      { name: "account_name", type: "string" },
      { name: "period_actual", type: "number" },
      { name: "comparison_actual", type: "number" },
      { name: "period_var", type: "number" },
      { name: "percent_var", type: "number" },
      { name: "period_budget", type: "number" },
      { name: "comparison_budget", type: "number" },
      { name: "budget_period_var", type: "number" },
      { name: "budget_percent_var", type: "number" },
      { name: "comparison_period_var", type: "number" },
      { name: "comparison_percent_var", type: "number" },
    ],
    filters: [
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "period_from", type: "date" },
      { name: "period_to", type: "date" },
      { name: "comparison_period_from", type: "date" },
      { name: "comparison_period_to", type: "date" },
      { name: "additional_account_types", type: "array" },
      { name: "gl_account_map_id", type: "integer" },
      { name: "level_of_detail", type: "string" },
    ],
  },
  {
    id: "twelve_month_cash_flow",
    title: "Cash Flow - 12 Month",
    summary: "Cash flow per account across twelve months plus a total.",
    tags: ["financial"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "account_name", type: "string" },
      { name: "account_code", type: "string" },
      { name: "months", type: "array" },
      { name: "total", type: "number" },
    ],
    filters: [
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "posted_on_from", type: "date" },
      { name: "posted_on_to", type: "date" },
      { name: "gl_account_map_id", type: "integer" },
      { name: "level_of_detail", type: "string" },
      { name: "include_zero_balance_gl_accounts", type: "string" },
      { name: "exclude_suppressed_fees", type: "string" },
    ],
  },
  {
    id: "cash_flow_detail",
    title: "Cash Flow Detail",
    summary: "Cash flow broken out to the transaction level.",
    tags: ["financial"],
    verified: true,
    source: "live-verified against Perpetual Realty account, 2026-08-25",
    columns: [
      { name: "account_name", type: "string" },
      { name: "property", type: "string" },
      { name: "unit", type: "string" },
      { name: "post_date", type: "date" },
      { name: "payee_name", type: "string" },
      { name: "type", type: "string" },
      { name: "txn_amount", type: "number" },
      { name: "reference", type: "string" },
      { name: "remarks", type: "string" },
      { name: "description", type: "string" },
      { name: "property_id", type: "integer" },
      { name: "unit_id", type: "integer" },
    ],
    filters: [
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "posted_on_from", type: "date" },
      { name: "posted_on_to", type: "date" },
      { name: "gl_account_map_id", type: "integer" },
      { name: "exclude_suppressed_fees", type: "string" },
    ],
  },
  {
    id: "chart_of_accounts",
    title: "Chart of Accounts",
    summary: "Every GL account with its type, offsets, and tax treatment.",
    tags: ["financial"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "number", type: "string" },
      { name: "account_name", type: "string" },
      { name: "account_type", type: "string" },
      { name: "sub_accountof", type: "string" },
      { name: "offset_account", type: "string" },
      { name: "subject_to_tax_authority", type: "boolean" },
      { name: "options", type: "string" },
      { name: "fund_account", type: "boolean" },
      { name: "hidden", type: "boolean" },
      { name: "gl_account_id", type: "integer" },
      { name: "sub_account_of_id", type: "integer" },
      { name: "offset_account_id", type: "integer" },
    ],
    filters: [
      { name: "columns", type: "array" },
    ],
  },
  {
    id: "income_statement_date_range",
    title: "Income Statement (Date Range)",
    summary: "Income and expense per account for a posting date range.",
    tags: ["financial"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "account_name", type: "string" },
      { name: "selected_period", type: "number" },
      { name: "account_number", type: "string" },
      { name: "gl_account_id", type: "integer" },
    ],
    filters: [
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "posted_on_from", type: "date" },
      { name: "posted_on_to", type: "date" },
      { name: "gl_account_map_id", type: "integer" },
      { name: "level_of_detail", type: "string" },
      { name: "include_zero_balance_gl_accounts", type: "string" },
      { name: "fund_type", type: "string" },
    ],
  },
  {
    id: "twelve_month_income_statement",
    title: "Income Statement - 12 Month",
    summary: "Income and expense per account across twelve months plus a total.",
    tags: ["financial"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "account_name", type: "string" },
      { name: "account_code", type: "string" },
      { name: "months", type: "array" },
      { name: "total", type: "number" },
    ],
    filters: [
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "fund_type", type: "string" },
      { name: "posted_on_from", type: "date" },
      { name: "posted_on_to", type: "date" },
      { name: "gl_account_map_id", type: "integer" },
      { name: "level_of_detail", type: "string" },
      { name: "include_zero_balance_gl_accounts", type: "string" },
    ],
  },
  {
    id: "expense_distribution",
    title: "Expense Distribution",
    summary: "Invoice level expenses by GL account, payee, property, and check.",
    tags: ["financial", "vendors"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "account", type: "string" },
      { name: "account_name", type: "string" },
      { name: "account_number", type: "string" },
      { name: "invoice_num", type: "string" },
      { name: "invoice_date", type: "date" },
      { name: "property_name", type: "string" },
      { name: "unit", type: "string" },
      { name: "property_address", type: "string" },
      { name: "payee", type: "string" },
      { name: "payable_account", type: "string" },
      { name: "amount", type: "number" },
      { name: "unpaid_amount", type: "number" },
      { name: "check_num", type: "string" },
      { name: "check_date", type: "date" },
      { name: "description", type: "string" },
    ],
    filters: [
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "party_contact_info.company_id", type: "integer" },
      { name: "posted_on_from", type: "date" },
      { name: "posted_on_to", type: "date" },
      { name: "gl_account_map_id", type: "integer" },
    ],
  },
  {
    id: "fixed_assets",
    title: "Fixed Assets",
    summary: "Tracked assets by property and unit with warranty and service dates.",
    tags: ["financial", "maintenance"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "asset_id", type: "integer" },
      { name: "serial_number", type: "string" },
      { name: "asset_type", type: "string" },
      { name: "property_name", type: "string" },
      { name: "property_id", type: "integer" },
      { name: "unit", type: "string" },
      { name: "unit_id", type: "integer" },
      { name: "warranty_expiration", type: "date" },
      { name: "placed_in_service", type: "date" },
      { name: "status", type: "string" },
      { name: "cost", type: "number" },
    ],
    filters: [
      { name: "property_visibility", type: "string" },
      { name: "unit_ids", type: "array" },
      { name: "property.property_id", type: "integer" },
      { name: "include_property_level_fixed_assets", type: "string" },
      { name: "asset_types", type: "string" },
      { name: "status", type: "string" },
    ],
  },
  {
    id: "loans",
    title: "Loans",
    summary: "Loans per property with balances, rates, escrow, and balloon terms.",
    tags: ["financial"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "property", type: "string" },
      { name: "property_name", type: "string" },
      { name: "property_id", type: "integer" },
      { name: "property_address", type: "string" },
      { name: "property_street", type: "string" },
      { name: "property_street2", type: "string" },
      { name: "property_city", type: "string" },
      { name: "property_state", type: "string" },
      { name: "property_zip", type: "string" },
      { name: "loan_id", type: "integer" },
      { name: "loan_number", type: "string" },
      { name: "vendor", type: "string" },
      { name: "loan_type", type: "string" },
      { name: "status", type: "string" },
      { name: "original_balance", type: "number" },
      { name: "current_balance", type: "number" },
      { name: "interest_rate_type", type: "string" },
      { name: "interest_rate", type: "number" },
      { name: "next_interest_rate", type: "number" },
      { name: "next_interest_rate_date", type: "date" },
      { name: "escrow", type: "number" },
      { name: "prepayment_penalty", type: "number" },
      { name: "balloon_amount", type: "number" },
    ],
    filters: [
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "reference_to", type: "date" },
      { name: "show_hidden_loans", type: "string" },
    ],
  },
  {
    id: "receivables_activity",
    title: "Receivables Activity",
    summary: "Receipts and payer portal activity over a receipt date range.",
    tags: ["financial", "tenants"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "property", type: "string" },
      { name: "property_name", type: "string" },
      { name: "property_id", type: "integer" },
      { name: "property_address", type: "string" },
      { name: "property_street", type: "string" },
      { name: "property_street2", type: "string" },
      { name: "property_city", type: "string" },
      { name: "property_state", type: "string" },
      { name: "property_zip", type: "string" },
      { name: "party", type: "string" },
      { name: "status", type: "string" },
      { name: "txn_amount", type: "number" },
      { name: "txn_remarks", type: "string" },
      { name: "txn_reference", type: "string" },
      { name: "txn_receipt_date", type: "date" },
      { name: "portal_activated", type: "boolean" },
      { name: "last_online_receipt_date", type: "date" },
      { name: "online_payments_recurring_count", type: "integer" },
      { name: "online_payments_recurring_total", type: "number" },
      { name: "move_in", type: "date" },
      { name: "emails", type: "array" },
      { name: "phone_numbers", type: "array" },
      { name: "certified_funds_only", type: "boolean" },
      { name: "opted_out_of_portal", type: "boolean" },
      { name: "payment_type", type: "string" },
      { name: "must_pay_balance_in_full", type: "boolean" },
      { name: "property_list", type: "array" },
      { name: "txn_id", type: "integer" },
      { name: "occupancy_id", type: "integer" },
      { name: "selected_tenant_id", type: "integer" },
      { name: "unit_id", type: "integer" },
    ],
    filters: [
      { name: "tenant_visibility", type: "string" },
      { name: "tenant_statuses", type: "array" },
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "receipt_date_from", type: "date" },
      { name: "receipt_date_to", type: "date" },
      { name: "manually_entered_only", type: "string" },
    ],
  },
  {
    id: "trial_balance_by_property",
    title: "Trial Balance by Property",
    summary: "Balance forward, debits, credits, and ending balance per account and property.",
    tags: ["financial"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "property_name", type: "string" },
      { name: "account_name", type: "string" },
      { name: "balance_forward", type: "number" },
      { name: "debit", type: "number" },
      { name: "credit", type: "number" },
      { name: "ending_balance", type: "number" },
      { name: "property_id", type: "integer" },
    ],
    filters: [
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "posted_on_from", type: "date" },
      { name: "posted_on_to", type: "date" },
      { name: "gl_account_map_id", type: "integer" },
    ],
  },
  {
    id: "vendor_ledger",
    title: "Vendor Ledger",
    summary: "Every bill, payment, and check for a vendor with full vendor detail.",
    tags: ["vendors", "financial"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "reference_number", type: "string" },
      { name: "bill_date", type: "date" },
      { name: "due_date", type: "date" },
      { name: "account", type: "string" },
      { name: "account_name", type: "string" },
      { name: "account_number", type: "string" },
      { name: "property", type: "string" },
      { name: "property_name", type: "string" },
      { name: "property_id", type: "integer" },
      { name: "property_address", type: "string" },
      { name: "property_street", type: "string" },
      { name: "property_street2", type: "string" },
      { name: "property_city", type: "string" },
      { name: "property_state", type: "string" },
      { name: "property_zip", type: "string" },
      { name: "vendor", type: "string" },
      { name: "vendor_name", type: "string" },
      { name: "vendor_id", type: "integer" },
      { name: "vendor_address", type: "string" },
      { name: "vendor_street", type: "string" },
      { name: "vendor_street2", type: "string" },
      { name: "vendor_city", type: "string" },
      { name: "vendor_state", type: "string" },
      { name: "vendor_zip", type: "string" },
      { name: "vendor_email", type: "string" },
      { name: "vendor_phone", type: "string" },
      { name: "vendor_fax", type: "string" },
      { name: "vendor_website", type: "string" },
      { name: "vendor_notes", type: "string" },
      { name: "vendor_terms", type: "string" },
      { name: "vendor_tax_id", type: "string" },
      { name: "vendor_1099", type: "boolean" },
      { name: "memo", type: "string" },
      { name: "amount", type: "number" },
      { name: "balance", type: "number" },
      { name: "status", type: "string" },
      { name: "bill_status", type: "string" },
      { name: "payment_status", type: "string" },
      { name: "payment_type", type: "string" },
      { name: "payment_method", type: "string" },
      { name: "check_number", type: "string" },
      { name: "check_date", type: "date" },
      { name: "check_amount", type: "number" },
      { name: "check_memo", type: "string" },
      { name: "check_status", type: "string" },
      { name: "purchase_order_number", type: "string" },
      { name: "purchase_order_id", type: "integer" },
      { name: "project", type: "string" },
      { name: "project_id", type: "integer" },
      { name: "service_request_id", type: "integer" },
      { name: "cost_center_name", type: "string" },
      { name: "cost_center_number", type: "string" },
      { name: "work_order_issue", type: "string" },
      { name: "work_order_id", type: "integer" },
      { name: "party_id", type: "integer" },
      { name: "party_type", type: "string" },
    ],
    filters: [
      { name: "vendor_id", type: "integer" },
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "occurred_on_from", type: "date" },
      { name: "occurred_on_to", type: "date" },
      { name: "reverse_transaction", type: "string" },
    ],
  },
  {
    id: "work_order_labor_summary",
    title: "Work Order Labor Summary",
    summary: "Maintenance tech labor logged against work orders.",
    tags: ["maintenance", "vendors"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "work_order_number", type: "string" },
      { name: "date", type: "date" },
      { name: "maintenance_tech", type: "string" },
      { name: "property_name", type: "string" },
      { name: "unit_name", type: "string" },
      { name: "start_time", type: "string" },
      { name: "end_time", type: "string" },
      { name: "worked_hours", type: "number" },
      { name: "hours", type: "number" },
      { name: "marked_after_hours", type: "boolean" },
      { name: "hours_difference", type: "number" },
      { name: "work_order_status", type: "string" },
      { name: "description", type: "string" },
      { name: "last_edited_by", type: "string" },
      { name: "unit_turn_id", type: "integer" },
      { name: "gl_account", type: "string" },
      { name: "last_bill_created_at", type: "date" },
      { name: "work_order_issue", type: "string" },
      { name: "property_id", type: "integer" },
      { name: "unit_id", type: "integer" },
      { name: "work_order_id", type: "integer" },
      { name: "service_request_id", type: "integer" },
      { name: "labor_detail_id", type: "integer" },
    ],
    filters: [
      { name: "property_visibility", type: "string" },
      { name: "maintenance_tech", type: "string" },
      { name: "labor_performed_from", type: "date" },
      { name: "labor_performed_to", type: "date" },
      { name: "unit_turn", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "work_order_statuses", type: "array" },
    ],
  },
  {
    id: "guest_card_inquiries",
    title: "Guest Card Inquiries",
    summary: "Prospect inquiries with source, status, preferences, and assigned user.",
    tags: ["leasing", "prospects"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "name", type: "string" },
      { name: "email_address", type: "string" },
      { name: "phone_number", type: "string" },
      { name: "received", type: "date" },
      { name: "last_activity_date", type: "date" },
      { name: "last_activity_type", type: "string" },
      { name: "latest_interest_date", type: "date" },
      { name: "latest_interest_source", type: "string" },
      { name: "status", type: "string" },
      { name: "move_in_preference", type: "date" },
      { name: "max_rent", type: "number" },
      { name: "bed_bath_preference", type: "string" },
      { name: "pet_preference", type: "string" },
      { name: "monthly_income", type: "number" },
      { name: "credit_score", type: "integer" },
      { name: "lead_type", type: "string" },
      { name: "source", type: "string" },
      { name: "property", type: "string" },
      { name: "unit", type: "string" },
      { name: "assigned_user", type: "string" },
      { name: "assigned_user_id", type: "integer" },
      { name: "guest_card_id", type: "integer" },
      { name: "inquiry_id", type: "integer" },
      { name: "property_id", type: "integer" },
      { name: "unit_id", type: "integer" },
      { name: "notes", type: "string" },
      { name: "tenant_id", type: "integer" },
      { name: "rental_application_id", type: "integer" },
      { name: "inquiry_type", type: "string" },
      { name: "total_interests_received", type: "integer" },
      { name: "interests_received_in_range", type: "integer" },
      { name: "showings", type: "integer" },
      { name: "inactive_reason", type: "string" },
      { name: "crm", type: "string" },
    ],
    filters: [
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "guest_card_sources", type: "array" },
      { name: "guest_card_statuses", type: "array" },
      { name: "guest_card_lead_types", type: "array" },
      { name: "assigned_user", type: "string" },
      { name: "assigned_user_visibility", type: "string" },
      { name: "guest_card_status", type: "string" },
      { name: "filter_date_range_by", type: "string" },
      { name: "received_on_from", type: "date" },
      { name: "received_on_to", type: "date" },
    ],
  },
  {
    id: "lease_expiration_detail",
    title: "Lease Expiration Detail By Month",
    summary: "Leases grouped by expiration month with rent and tenant detail.",
    tags: ["leasing", "occupancy"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "property", type: "string" },
      { name: "property_name", type: "string" },
      { name: "property_id", type: "integer" },
      { name: "property_address", type: "string" },
      { name: "property_street", type: "string" },
      { name: "property_street2", type: "string" },
      { name: "property_city", type: "string" },
      { name: "property_state", type: "string" },
      { name: "property_zip", type: "string" },
      { name: "unit", type: "string" },
      { name: "unit_tags", type: "array" },
      { name: "unit_type", type: "string" },
      { name: "move_in", type: "date" },
      { name: "lease_expires", type: "date" },
      { name: "lease_expires_month", type: "string" },
      { name: "market_rent", type: "number" },
      { name: "sqft", type: "integer" },
      { name: "tenant_name", type: "string" },
      { name: "deposit", type: "number" },
      { name: "rent", type: "number" },
      { name: "phone_numbers", type: "array" },
      { name: "unit_id", type: "integer" },
      { name: "occupancy_id", type: "integer" },
      { name: "tenant_id", type: "integer" },
      { name: "owner_agent", type: "string" },
      { name: "tenant_agent", type: "string" },
      { name: "rent_status", type: "string" },
      { name: "legal_rent", type: "number" },
      { name: "owners_phone_number", type: "string" },
      { name: "owners", type: "string" },
      { name: "last_rent_increase", type: "date" },
      { name: "next_rent_adjustment", type: "date" },
      { name: "next_rent_increase", type: "number" },
      { name: "lease_sign_date", type: "date" },
      { name: "last_lease_renewal", type: "date" },
      { name: "notice_given_date", type: "date" },
      { name: "move_out", type: "date" },
      { name: "tenant_tags", type: "array" },
      { name: "affordable_program", type: "boolean" },
      { name: "computed_market_rent", type: "number" },
    ],
    filters: [
      { name: "from_date", type: "date" },
      { name: "to_date", type: "date" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "unit_visibility", type: "string" },
      { name: "tags", type: "array" },
      { name: "filter_lease_date_range_by", type: "string" },
      { name: "exclude_occupancies_with_move_out", type: "string" },
      { name: "exclude_month_to_month", type: "string" },
    ],
    filterCaveats:
      "from_date, to_date and exclude_month_to_month are accepted with 200 and never applied. " +
      "Verified live: scoped to one property the report returns the same 3 rows with and without " +
      "an impossible 1990 range, and date_from/date_to, lease_expiration_from/to, " +
      "occurred_on_from/to, expiration_from/to and plain from/to were all tried and none filter " +
      "either. The properties.* filters do work, so scope by property and narrow by the " +
      "lease_expires column client-side.",
  },
  {
    id: "leasing_funnel_performance",
    title: "Leasing Funnel Performance",
    summary: "Inquiry to lease conversion rates per property and leasing agent.",
    tags: ["leasing", "prospects"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "assigned_inquiry_owner", type: "string" },
      { name: "assigned_inquiry_owner_id", type: "integer" },
      { name: "property_name", type: "string" },
      { name: "property_id", type: "integer" },
      { name: "inquiries", type: "integer" },
      { name: "completed_showings", type: "integer" },
      { name: "cancelled_showings", type: "integer" },
      { name: "rental_apps", type: "integer" },
      { name: "decision_pending", type: "integer" },
      { name: "approved", type: "integer" },
      { name: "denied", type: "integer" },
      { name: "cancelled", type: "integer" },
      { name: "signed_leases", type: "integer" },
      { name: "move_ins", type: "integer" },
      { name: "inquiries_to_completed_showings", type: "number" },
      { name: "completed_showings_to_apps", type: "number" },
      { name: "approved_app_rate", type: "number" },
      { name: "apps_to_signed_leases", type: "number" },
      { name: "inquiries_to_leases", type: "number" },
    ],
    filters: [
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "date_from", type: "date" },
      { name: "date_to", type: "date" },
      { name: "assigned_user_visibility", type: "string" },
      { name: "assigned_user", type: "string" },
    ],
    filterCaveats:
      "date_from and date_to are accepted with 200 and never applied, so every funnel metric is " +
      "lifetime-to-date no matter what range is asked for. Verified live: unfiltered, a 1990 " +
      "range, an August 2026 range and a full 2026 range all returned the same 24 rows and the " +
      "same 187 total inquiries. The properties.* filters do work.",
  },
  {
    id: "leasing_summary",
    title: "Leasing Summary",
    summary: "Leasing activity counts per unit type over a date range.",
    tags: ["leasing"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "unit_type", type: "string" },
      { name: "number_of_units", type: "integer" },
      { name: "number_of_model_units", type: "integer" },
      { name: "inquiries_received", type: "integer" },
      { name: "showings_completed", type: "integer" },
      { name: "applications_received", type: "integer" },
      { name: "move_ins", type: "integer" },
      { name: "move_outs", type: "integer" },
      { name: "leased", type: "integer" },
      { name: "vacancy_postings", type: "integer" },
      { name: "number_of_active_campaigns", type: "integer" },
      { name: "number_of_ended_campaigns", type: "integer" },
    ],
    filters: [
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "unit_visibility", type: "string" },
      { name: "posted_on_from", type: "date" },
      { name: "posted_on_to", type: "date" },
    ],
  },
  {
    id: "prospect_source_tracking",
    title: "Property Source Tracking",
    summary: "Inquiry, showing, application, and conversion counts per marketing source.",
    tags: ["leasing", "prospects"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "source", type: "string" },
      { name: "guest_card_inquiries", type: "integer" },
      { name: "showings", type: "integer" },
      { name: "applications", type: "integer" },
      { name: "approved_applications", type: "integer" },
      { name: "converted_tenants", type: "integer" },
    ],
    filters: [
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "unit_visibility", type: "string" },
      { name: "received_on_from", type: "date" },
      { name: "received_on_to", type: "date" },
    ],
  },
  {
    id: "renewal_summary",
    title: "Renewal Summary",
    summary: "Renewal offers with previous and new lease terms, rent change, and status.",
    tags: ["leasing"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "unit_name", type: "string" },
      { name: "property", type: "string" },
      { name: "property_name", type: "string" },
      { name: "property_id", type: "integer" },
      { name: "property_address", type: "string" },
      { name: "property_street", type: "string" },
      { name: "property_street2", type: "string" },
      { name: "property_city", type: "string" },
      { name: "property_state", type: "string" },
      { name: "property_zip", type: "string" },
      { name: "unit_type", type: "string" },
      { name: "unit_id", type: "integer" },
      { name: "occupancy_id", type: "integer" },
      { name: "tenant_name", type: "string" },
      { name: "lease_start", type: "date" },
      { name: "lease_end", type: "date" },
      { name: "previous_lease_start", type: "date" },
      { name: "previous_lease_end", type: "date" },
      { name: "previous_rent", type: "number" },
      { name: "rent", type: "number" },
      { name: "respond_by_date", type: "date" },
      { name: "renewal_sent_date", type: "date" },
      { name: "countersigned_date", type: "date" },
      { name: "automatic_renewal_date", type: "date" },
      { name: "percent_difference", type: "number" },
      { name: "dollar_difference", type: "number" },
      { name: "status", type: "string" },
      { name: "term", type: "string" },
      { name: "lease_start_month", type: "string" },
      { name: "tenant_id", type: "integer" },
      { name: "tenant_tags", type: "array" },
      { name: "tenant_agent", type: "string" },
      { name: "notice_given_date", type: "date" },
      { name: "move_out", type: "date" },
    ],
    filters: [
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "unit_visibility", type: "string" },
      { name: "start_on_from", type: "date" },
      { name: "start_on_to", type: "date" },
      { name: "statuses", type: "array" },
      { name: "include_tenant_transfers", type: "string" },
    ],
  },
  {
    id: "rent_roll_itemized",
    title: "Rent Roll Itemized",
    summary: "Rent roll with itemized charges, amenities, and rent increase schedule per unit.",
    tags: ["occupancy", "leasing"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "property", type: "string" },
      { name: "property_name", type: "string" },
      { name: "property_id", type: "integer" },
      { name: "property_address", type: "string" },
      { name: "property_street", type: "string" },
      { name: "property_street2", type: "string" },
      { name: "property_city", type: "string" },
      { name: "property_state", type: "string" },
      { name: "property_zip", type: "string" },
      { name: "property_type", type: "string" },
      { name: "occupancy_id", type: "integer" },
      { name: "unit_id", type: "integer" },
      { name: "unit", type: "string" },
      { name: "unit_tags", type: "array" },
      { name: "unit_type", type: "string" },
      { name: "bd_ba", type: "string" },
      { name: "tenant", type: "string" },
      { name: "status", type: "string" },
      { name: "sqft", type: "integer" },
      { name: "market_rent", type: "number" },
      { name: "computed_market_rent", type: "number" },
      { name: "advertised_rent", type: "number" },
      { name: "total", type: "number" },
      { name: "other_charges", type: "number" },
      { name: "monthly_rent_square_ft", type: "number" },
      { name: "annual_rent_square_ft", type: "number" },
      { name: "deposit", type: "number" },
      { name: "lease_from", type: "date" },
      { name: "lease_to", type: "date" },
      { name: "last_rent_increase", type: "date" },
      { name: "next_rent_adjustment", type: "date" },
      { name: "next_rent_increase_amount", type: "number" },
      { name: "next_rent_increase", type: "date" },
      { name: "move_in", type: "date" },
      { name: "move_out", type: "date" },
      { name: "past_due", type: "number" },
      { name: "nsf", type: "integer" },
      { name: "late", type: "integer" },
      { name: "amenities", type: "array" },
      { name: "additional_tenants", type: "array" },
      { name: "monthly_charges", type: "number" },
      { name: "rent_ready", type: "boolean" },
      { name: "rent_status", type: "string" },
      { name: "legal_rent", type: "number" },
      { name: "preferential_rent", type: "number" },
      { name: "tenant_tags", type: "array" },
      { name: "tenant_agent", type: "string" },
      { name: "property_group_id", type: "integer" },
      { name: "portfolio_id", type: "integer" },
    ],
    filters: [
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "unit_visibility", type: "string" },
      { name: "tags", type: "array" },
      { name: "gl_account_ids", type: "array" },
      { name: "as_of_date", type: "date" },
    ],
  },
  {
    id: "owner_leasing",
    title: "Owner Leasing",
    summary: "Owner facing leasing activity per unit, from inquiry through converted tenant.",
    tags: ["leasing", "owners"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "property", type: "string" },
      { name: "unit", type: "string" },
      { name: "applied_to", type: "string" },
      { name: "unit_type", type: "string" },
      { name: "market_rent", type: "number" },
      { name: "inquiries", type: "integer" },
      { name: "showings", type: "integer" },
      { name: "applications", type: "integer" },
      { name: "approved_applications", type: "integer" },
      { name: "converted_tenants", type: "integer" },
      { name: "property_id", type: "integer" },
      { name: "unit_id", type: "integer" },
      { name: "computed_market_rent", type: "number" },
    ],
    filters: [
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "received_on_from", type: "date" },
      { name: "received_on_to", type: "date" },
      { name: "unit_visibility", type: "string" },
      { name: "include_units_which_are_not_rent_ready", type: "string" },
      { name: "include_units_which_are_hidden_from_the_vacancies_dashboard", type: "string" },
    ],
  },
  {
    id: "owner_directory",
    title: "Owner Directory",
    summary: "All owners with contact detail, payment settings, and properties owned.",
    tags: ["owners"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "name", type: "string" },
      { name: "phone_numbers", type: "array" },
      { name: "email", type: "string" },
      { name: "alternative_payee", type: "string" },
      { name: "payment_type", type: "string" },
      { name: "last_payment_date", type: "date" },
      { name: "hold_payments", type: "boolean" },
      { name: "send_owner_packets_by_email", type: "boolean" },
      { name: "properties_owned", type: "string" },
      { name: "tags", type: "array" },
      { name: "last_packet_sent", type: "date" },
      { name: "address", type: "string" },
      { name: "street", type: "string" },
      { name: "street2", type: "string" },
      { name: "city", type: "string" },
      { name: "state", type: "string" },
      { name: "zip", type: "string" },
      { name: "country", type: "string" },
      { name: "owner_id", type: "integer" },
      { name: "notes_for_the_owner", type: "string" },
      { name: "first_name", type: "string" },
      { name: "last_name", type: "string" },
      { name: "created_by", type: "string" },
    ],
    filters: [
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "tags", type: "array" },
      { name: "owner_visibility", type: "string" },
      { name: "created_by", type: "string" },
    ],
  },
  {
    id: "property_directory",
    title: "Property Directory",
    summary: "Every property with address, fee structure, and management settings.",
    tags: ["properties"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "property", type: "string" },
      { name: "property_name", type: "string" },
      { name: "property_id", type: "integer" },
      { name: "property_address", type: "string" },
      { name: "property_street", type: "string" },
      { name: "property_street2", type: "string" },
      { name: "property_city", type: "string" },
      { name: "property_state", type: "string" },
      { name: "property_zip", type: "string" },
      { name: "property_county", type: "string" },
      { name: "market_rent", type: "number" },
      { name: "units", type: "integer" },
      { name: "sqft", type: "integer" },
      { name: "management_flat_fee", type: "number" },
      { name: "management_fee_percent", type: "number" },
      { name: "minimum_fee", type: "number" },
      { name: "maximum_fee", type: "number" },
      { name: "waive_fees_when_vacant", type: "boolean" },
      { name: "reserve", type: "number" },
      { name: "home_warranty_expiration", type: "date" },
      { name: "insurance_expiration", type: "date" },
      { name: "tax_year_end", type: "string" },
      { name: "tax_authority", type: "string" },
      { name: "owners_phone_number", type: "string" },
      { name: "payer_name", type: "string" },
      { name: "description", type: "string" },
      { name: "portfolio", type: "string" },
      { name: "property_group_id", type: "integer" },
      { name: "portfolio_id", type: "integer" },
      { name: "visibility", type: "string" },
      { name: "maintenance_limit", type: "number" },
      { name: "maintenance_notes", type: "string" },
      { name: "site_manager_name", type: "string" },
      { name: "site_manager_phone_number", type: "string" },
      { name: "management_fee_type", type: "string" },
      { name: "lease_fee_type", type: "string" },
      { name: "owner_payment_type", type: "string" },
      { name: "property_type", type: "string" },
      { name: "property_created_on", type: "date" },
      { name: "property_created_by", type: "string" },
      { name: "owners", type: "string" },
      { name: "prepayment_type", type: "string" },
      { name: "late_fee_type", type: "string" },
      { name: "late_fee_base_amount", type: "number" },
      { name: "late_fee_daily_amount", type: "number" },
      { name: "late_fee_grace_period", type: "integer" },
      { name: "max_daily_late_fees_amount", type: "number" },
      { name: "ignore_partial_payments", type: "boolean" },
      { name: "admin_fee_amount", type: "number" },
      { name: "year_built", type: "integer" },
      { name: "agent_of_record", type: "string" },
      { name: "property_class", type: "string" },
      { name: "online_maintenance_request_instructions", type: "string" },
      { name: "amenities", type: "array" },
      { name: "listing_type", type: "string" },
    ],
    filters: [
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
    ],
  },
  {
    id: "property_group_directory",
    title: "Property Group Directory",
    summary: "Properties mapped to their property group and portfolio.",
    tags: ["properties"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "property", type: "string" },
      { name: "property_name", type: "string" },
      { name: "property_id", type: "integer" },
      { name: "property_address", type: "string" },
      { name: "property_street", type: "string" },
      { name: "property_street2", type: "string" },
      { name: "property_city", type: "string" },
      { name: "property_state", type: "string" },
      { name: "property_zip", type: "string" },
      { name: "property_county", type: "string" },
      { name: "property_group_name", type: "string" },
      { name: "portfolio", type: "string" },
      { name: "property_group_id", type: "integer" },
      { name: "portfolio_id", type: "integer" },
    ],
    filters: [
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "orphans_only", type: "string" },
    ],
  },
  {
    id: "property_performance",
    title: "Property Performance",
    summary: "Per property GL account performance over a period.",
    tags: ["properties", "financial"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "property", type: "string" },
      { name: "property_name", type: "string" },
      { name: "property_id", type: "integer" },
      { name: "property_address", type: "string" },
      { name: "property_street", type: "string" },
      { name: "property_street2", type: "string" },
      { name: "property_city", type: "string" },
      { name: "property_state", type: "string" },
      { name: "property_zip", type: "string" },
      { name: "units", type: "integer" },
      { name: "gl_accounts", type: "array" },
      { name: "commission_percent", type: "number" },
      { name: "site_manager", type: "string" },
      { name: "property_group_id", type: "integer" },
      { name: "portfolio_id", type: "integer" },
    ],
    filters: [
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "gl_account_ids", type: "array" },
      { name: "period_from", type: "date" },
      { name: "period_to", type: "date" },
      { name: "report_format", type: "string" },
    ],
  },
  {
    id: "occupancy_summary",
    title: "Occupancy Summary",
    summary: "Occupied, vacant, and notice unit counts per unit type as of a date.",
    tags: ["occupancy"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "unit_type", type: "string" },
      { name: "number_of_units", type: "integer" },
      { name: "occupied", type: "integer" },
      { name: "percent_occupied", type: "number" },
      { name: "average_square_feet", type: "number" },
      { name: "average_market_rent", type: "number" },
      { name: "vacant_rented", type: "integer" },
      { name: "vacant_unrented", type: "integer" },
      { name: "notice_rented", type: "integer" },
      { name: "notice_unrented", type: "integer" },
      { name: "average_rent", type: "number" },
      { name: "property", type: "string" },
      { name: "property_id", type: "integer" },
    ],
    filters: [
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "unit_visibility", type: "string" },
      { name: "as_of_date", type: "date" },
    ],
  },
  {
    id: "unit_directory",
    title: "Unit Directory",
    summary: "Every unit with marketing detail, rent, amenities, and rentability.",
    tags: ["units"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "property", type: "string" },
      { name: "property_name", type: "string" },
      { name: "property_id", type: "integer" },
      { name: "unit_address", type: "string" },
      { name: "unit_street", type: "string" },
      { name: "unit_street2", type: "string" },
      { name: "unit_city", type: "string" },
      { name: "unit_state", type: "string" },
      { name: "unit_zip", type: "string" },
      { name: "unit_name", type: "string" },
      { name: "market_rent", type: "number" },
      { name: "marketing_title", type: "string" },
      { name: "marketing_description", type: "string" },
      { name: "advertised_rent", type: "number" },
      { name: "posted_to_website", type: "boolean" },
      { name: "posted_to_internet", type: "boolean" },
      { name: "you_tube_url", type: "string" },
      { name: "default_deposit", type: "number" },
      { name: "sqft", type: "integer" },
      { name: "bedrooms", type: "number" },
      { name: "bathrooms", type: "number" },
      { name: "unit_tags", type: "array" },
      { name: "unit_type", type: "string" },
      { name: "created_on", type: "date" },
      { name: "rentable", type: "boolean" },
      { name: "rubs_enabled", type: "boolean" },
      { name: "rubs_enabled_on", type: "date" },
      { name: "description", type: "string" },
      { name: "rent_status", type: "string" },
      { name: "legal_rent", type: "number" },
      { name: "application_fee", type: "number" },
      { name: "rent_ready", type: "boolean" },
      { name: "unit_id", type: "integer" },
      { name: "computed_market_rent", type: "number" },
      { name: "ready_for_showing_on", type: "date" },
      { name: "visibility", type: "string" },
      { name: "portfolio_id", type: "integer" },
      { name: "unit_amenities", type: "array" },
      { name: "unit_appliances", type: "array" },
      { name: "unit_utilities", type: "array" },
      { name: "billed_as", type: "string" },
    ],
    filters: [
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "unit_visibility", type: "string" },
      { name: "tags", type: "array" },
    ],
  },
  {
    id: "unit_inspection",
    title: "Unit Inspection",
    summary: "Units with their last inspection date and current tenant.",
    tags: ["units", "maintenance"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "property", type: "string" },
      { name: "property_name", type: "string" },
      { name: "property_id", type: "integer" },
      { name: "property_address", type: "string" },
      { name: "property_street", type: "string" },
      { name: "property_street2", type: "string" },
      { name: "property_city", type: "string" },
      { name: "property_state", type: "string" },
      { name: "property_zip", type: "string" },
      { name: "unit_name", type: "string" },
      { name: "last_inspection_date", type: "date" },
      { name: "tenant_name", type: "string" },
      { name: "tenant_primary_phone_number", type: "string" },
      { name: "move_in_date", type: "date" },
      { name: "move_out_date", type: "date" },
      { name: "unit_id", type: "integer" },
      { name: "occupancy_id", type: "integer" },
      { name: "rentable", type: "boolean" },
      { name: "unit_tags", type: "array" },
    ],
    filters: [
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "unit_visibility", type: "string" },
      { name: "last_inspection_on_from", type: "date" },
      { name: "include_blank_inspection_date", type: "string" },
    ],
  },
  {
    id: "unit_vacancy",
    title: "Unit Vacancy Detail",
    summary: "Vacant units with days vacant, asking rent, and availability dates.",
    tags: ["units", "occupancy"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "advertised_rent", type: "number" },
      { name: "posted_to_website", type: "boolean" },
      { name: "posted_to_internet", type: "boolean" },
      { name: "property", type: "string" },
      { name: "property_name", type: "string" },
      { name: "amenities", type: "array" },
      { name: "lockbox_enabled", type: "boolean" },
      { name: "affordable_program", type: "boolean" },
      { name: "address", type: "string" },
      { name: "street", type: "string" },
      { name: "street2", type: "string" },
      { name: "city", type: "string" },
      { name: "state", type: "string" },
      { name: "zip", type: "string" },
      { name: "unit", type: "string" },
      { name: "unit_tags", type: "array" },
      { name: "unit_type", type: "string" },
      { name: "bed_and_bath", type: "string" },
      { name: "sqft", type: "integer" },
      { name: "unit_status", type: "string" },
      { name: "rent_ready", type: "boolean" },
      { name: "days_vacant", type: "integer" },
      { name: "last_rent", type: "number" },
      { name: "schd_rent", type: "number" },
      { name: "new_rent", type: "number" },
      { name: "last_move_in", type: "date" },
      { name: "last_move_out", type: "date" },
      { name: "available_on", type: "date" },
      { name: "next_move_in", type: "date" },
      { name: "description", type: "string" },
      { name: "amenities_price", type: "number" },
      { name: "computed_market_rent", type: "number" },
      { name: "ready_for_showing_on", type: "date" },
      { name: "unit_turn_target_date", type: "date" },
      { name: "property_id", type: "integer" },
      { name: "unit_id", type: "integer" },
    ],
    filters: [
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "property_visibility", type: "string" },
      { name: "tags", type: "array" },
    ],
  },
  {
    id: "delinquency_as_of",
    title: "Delinquency (As Of)",
    summary: "Tenant balances aged as of a date, with delinquency notes and collections status.",
    tags: ["financial", "tenants"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "unit", type: "string" },
      { name: "name", type: "string" },
      { name: "tenant_status", type: "string" },
      { name: "tags", type: "array" },
      { name: "phone_numbers", type: "array" },
      { name: "move_in", type: "date" },
      { name: "move_out", type: "date" },
      { name: "primary_tenant_email", type: "string" },
      { name: "unit_type", type: "string" },
      { name: "property", type: "string" },
      { name: "property_name", type: "string" },
      { name: "property_id", type: "integer" },
      { name: "property_address", type: "string" },
      { name: "property_street", type: "string" },
      { name: "property_street2", type: "string" },
      { name: "property_city", type: "string" },
      { name: "property_state", type: "string" },
      { name: "property_zip", type: "string" },
      { name: "amount_receivable", type: "number" },
      { name: "delinquent_subsidy_amount", type: "number" },
      { name: "00_to30", type: "number" },
      { name: "30_plus", type: "number" },
      { name: "30_to60", type: "number" },
      { name: "60_plus", type: "number" },
      { name: "60_to90", type: "number" },
      { name: "90_plus", type: "number" },
      { name: "this_month", type: "number" },
      { name: "last_month", type: "number" },
      { name: "month_before_last", type: "number" },
      { name: "delinquent_rent", type: "number" },
      { name: "delinquency_notes", type: "string" },
      { name: "certified_funds_only", type: "boolean" },
      { name: "in_collections", type: "boolean" },
      { name: "collections_agency", type: "string" },
      { name: "unit_id", type: "integer" },
      { name: "occupancy_id", type: "integer" },
      { name: "property_group_id", type: "integer" },
    ],
    filters: [
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "occurred_on_to", type: "date" },
      { name: "delinquency_note_range", type: "string" },
      { name: "tenant_statuses", type: "array" },
      { name: "tags", type: "array" },
      { name: "amount_owed_in_account", type: "string" },
      { name: "balance_operator.amount", type: "number" },
      { name: "balance_operator.comparator", type: "string" },
    ],
  },
  {
    id: "resident_financial_activity",
    title: "Resident Financial Activity",
    summary: "Resident transaction history including voids and payment methods.",
    tags: ["financial", "tenants"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "property_id", type: "integer" },
      { name: "property_name", type: "string" },
      { name: "unit_id", type: "integer" },
      { name: "unit_number", type: "string" },
      { name: "resident_id", type: "integer" },
      { name: "resident_name", type: "string" },
      { name: "transaction_id", type: "integer" },
      { name: "transaction_type", type: "string" },
      { name: "transaction_date", type: "date" },
      { name: "transaction_description", type: "string" },
      { name: "transaction_amount", type: "number" },
      { name: "transaction_balance", type: "number" },
      { name: "transaction_status", type: "string" },
      { name: "payment_method", type: "string" },
      { name: "check_number", type: "string" },
      { name: "reference_number", type: "string" },
      { name: "created_by", type: "string" },
      { name: "created_at", type: "date" },
      { name: "updated_at", type: "date" },
      { name: "is_void", type: "boolean" },
      { name: "voided_at", type: "date" },
      { name: "voided_by", type: "string" },
      { name: "void_reason", type: "string" },
    ],
    filters: [
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "occurred_on_from", type: "date" },
      { name: "occurred_on_to", type: "date" },
      { name: "include_voided", type: "boolean" },
    ],
  },
  {
    id: "tenant_ledger",
    title: "Tenant Ledger",
    summary: "Debits, credits, and running balance for selected tenant occupancies.",
    tags: ["financial", "tenants"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "date", type: "date" },
      { name: "payer", type: "string" },
      { name: "description", type: "string" },
      { name: "debit", type: "number" },
      { name: "credit", type: "number" },
      { name: "credit_debit_balance", type: "number" },
    ],
    filters: [
      { name: "parties_ids.occupancies_ids", type: "array" },
      { name: "occurred_on_from", type: "date" },
      { name: "occurred_on_to", type: "date" },
      { name: "transactions_shown", type: "string" },
    ],
  },
  {
    id: "cancelled_processes",
    title: "Cancelled Workflows",
    summary: "Cancelled workflows with who cancelled them and why.",
    tags: ["workflows"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "attachable_for", type: "string" },
      { name: "property", type: "string" },
      { name: "workflow_name", type: "string" },
      { name: "cancelled_date", type: "date" },
      { name: "cancelled_by", type: "string" },
      { name: "cancellation_reason", type: "string" },
    ],
    filters: [
      { name: "attachables.properties_ids", type: "array" },
      { name: "attachables.units_ids", type: "array" },
      { name: "attachables.tenants_ids", type: "array" },
      { name: "attachables.owners_ids", type: "array" },
      { name: "attachables.rental_applications_ids", type: "array" },
      { name: "attachables.guest_cards_ids", type: "array" },
      { name: "attachables.service_requests_ids", type: "array" },
      { name: "attachables.vendors_ids", type: "array" },
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "process_template", type: "string" },
      { name: "workflow_step", type: "string" },
      { name: "assigned_user", type: "string" },
      { name: "date_range_from", type: "date" },
      { name: "date_range_to", type: "date" },
      { name: "cancelled_by", type: "string" },
    ],
  },
  {
    id: "completed_processes",
    title: "Completed Workflows",
    summary: "Completed workflows and their completion dates.",
    tags: ["workflows"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "attachable_for", type: "string" },
      { name: "property", type: "string" },
      { name: "workflow_name", type: "string" },
      { name: "completed_date", type: "date" },
    ],
    filters: [
      { name: "attachables.properties_ids", type: "array" },
      { name: "attachables.units_ids", type: "array" },
      { name: "attachables.tenants_ids", type: "array" },
      { name: "attachables.owners_ids", type: "array" },
      { name: "attachables.rental_applications_ids", type: "array" },
      { name: "attachables.guest_cards_ids", type: "array" },
      { name: "attachables.service_requests_ids", type: "array" },
      { name: "attachables.vendors_ids", type: "array" },
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "process_template", type: "string" },
      { name: "workflow_step", type: "string" },
      { name: "assigned_user", type: "string" },
      { name: "date_range_from", type: "date" },
      { name: "date_range_to", type: "date" },
    ],
  },
  {
    id: "in_progress_workflows",
    title: "In-Progress Workflows",
    summary: "Open workflows with their current step, assignee, and due date.",
    tags: ["workflows"],
    verified: true,
    source: "cryptocultcurt-v2 (ISC, attributed)",
    columns: [
      { name: "attachable_for", type: "string" },
      { name: "property", type: "string" },
      { name: "workflow_name", type: "string" },
      { name: "current_step", type: "string" },
      { name: "status", type: "string" },
      { name: "due_date", type: "date" },
      { name: "assigned_to", type: "string" },
    ],
    filters: [
      { name: "attachables.properties_ids", type: "array" },
      { name: "attachables.units_ids", type: "array" },
      { name: "attachables.tenants_ids", type: "array" },
      { name: "attachables.owners_ids", type: "array" },
      { name: "attachables.rental_applications_ids", type: "array" },
      { name: "attachables.guest_cards_ids", type: "array" },
      { name: "attachables.service_requests_ids", type: "array" },
      { name: "attachables.vendors_ids", type: "array" },
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "process_template", type: "string" },
      { name: "workflow_step", type: "string" },
      { name: "assigned_user", type: "string" },
      { name: "date_range_from", type: "date" },
      { name: "date_range_to", type: "date" },
    ],
  },
  // rental_applications, security_deposit_funds_detail, and tenant_directory carry a different
  // provenance: CryptoCultCurt claimed columns for these three that a live POST against the real
  // account proved fabricated (templated boilerplate blocks absent from the actual response), so
  // their columns below were re-verified independently from that live response. Their filter names
  // were never in question and still come from CryptoCultCurt.
  {
    id: "rental_applications",
    title: "Rental Applications",
    summary: "Rental applications with applicant, employment, residence history, and decision status.",
    tags: ["leasing", "prospects"],
    verified: true,
    source: "live-verified against Perpetual Realty account, 2026-08-25",
    columns: [
      { name: "additional_incomes", type: "array" },
      { name: "applicant_reported_source", type: "string" },
      { name: "applicants", type: "array" },
      { name: "application_fee_paid", type: "boolean" },
      { name: "application_status", type: "string" },
      { name: "applying_for", type: "string" },
      { name: "approved_at", type: "date" },
      { name: "assigned_user", type: "string" },
      { name: "assigned_user_id", type: "integer" },
      { name: "campaign_title", type: "string" },
      { name: "canceled_at", type: "date" },
      { name: "created_by", type: "string" },
      { name: "current_address1", type: "string" },
      { name: "current_address2", type: "string" },
      { name: "current_city", type: "string" },
      { name: "current_monthly_rent", type: "number" },
      { name: "current_state", type: "string" },
      { name: "current_zip", type: "string" },
      { name: "decision_made_at", type: "date" },
      { name: "denied_at", type: "date" },
      { name: "desired_move_in", type: "date" },
      { name: "email", type: "string" },
      { name: "employer_name", type: "string" },
      { name: "employer_phone_number", type: "string" },
      { name: "inquiry_id", type: "integer" },
      { name: "landlord_email", type: "string" },
      { name: "landlord_name", type: "string" },
      { name: "landlord_phone_number", type: "string" },
      { name: "lead_source", type: "string" },
      { name: "lease_end_date", type: "date" },
      { name: "lease_start_date", type: "date" },
      { name: "monthly_salary", type: "number" },
      { name: "move_in_date", type: "date" },
      { name: "pets_kinds", type: "array" },
      { name: "pets_names", type: "array" },
      { name: "pets_weights", type: "array" },
      { name: "phone_number", type: "string" },
      { name: "position_held", type: "string" },
      { name: "previous1_address1", type: "string" },
      { name: "previous1_address2", type: "string" },
      { name: "previous2_address1", type: "string" },
      { name: "previous2_address2", type: "string" },
      { name: "previous_city1", type: "string" },
      { name: "previous_city2", type: "string" },
      { name: "previous_landlord_email1", type: "string" },
      { name: "previous_landlord_email2", type: "string" },
      { name: "previous_landlord_name1", type: "string" },
      { name: "previous_landlord_name2", type: "string" },
      { name: "previous_landlord_phone_number1", type: "string" },
      { name: "previous_landlord_phone_number2", type: "string" },
      { name: "previous_monthly_rent1", type: "number" },
      { name: "previous_monthly_rent2", type: "number" },
      { name: "previous_resided_from1", type: "date" },
      { name: "previous_resided_from2", type: "date" },
      { name: "previous_resided_to1", type: "date" },
      { name: "previous_resided_to2", type: "date" },
      { name: "previous_state1", type: "string" },
      { name: "previous_state2", type: "string" },
      { name: "previous_zip1", type: "string" },
      { name: "previous_zip2", type: "string" },
      { name: "property_id", type: "integer" },
      { name: "property_name", type: "string" },
      { name: "reason_for_status", type: "string" },
      { name: "received", type: "date" },
      { name: "rental_application_group_id", type: "integer" },
      { name: "rental_application_id", type: "integer" },
      { name: "rental_application_integration_id", type: "string" },
      { name: "resided_from", type: "date" },
      { name: "resided_to", type: "date" },
      { name: "screened_on", type: "date" },
      { name: "screening", type: "string" },
      { name: "status", type: "string" },
      { name: "tenant_id", type: "integer" },
      { name: "time_to_conversion", type: "number" },
      { name: "unit_address", type: "string" },
      { name: "unit_city", type: "string" },
      { name: "unit_id", type: "integer" },
      { name: "unit_name", type: "string" },
      { name: "unit_state", type: "string" },
      { name: "unit_street", type: "string" },
      { name: "unit_street2", type: "string" },
      { name: "unit_title", type: "string" },
      { name: "unit_type", type: "string" },
      { name: "unit_zip", type: "string" },
      { name: "years_worked", type: "number" },
    ],
    filters: [
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "received_on_from", type: "date" },
      { name: "received_on_to", type: "date" },
      { name: "rental_application_statuses", type: "array" },
      { name: "sources", type: "array" },
    ],
    filterCaveats:
      "The status filter is named rental_application_statuses. A filter named statuses is " +
      "accepted with 200 and never applied. Verified live: statuses ['Converted'] returned all " +
      "43 applications, rental_application_statuses ['Converted'] returned 9. Valid values are " +
      "the status column's own words: Converted, Canceled, Denied, Approved, Decision Pending.",
  },
  {
    id: "security_deposit_funds_detail",
    title: "Security Deposit Funds Detail",
    summary: "Security deposit funds held per occupancy as of a date.",
    tags: ["financial", "tenants"],
    verified: true,
    source: "live-verified against Perpetual Realty account, 2026-08-25",
    columns: [
      { name: "amount", type: "number" },
      { name: "move_in", type: "date" },
      { name: "move_out", type: "date" },
      { name: "occupancy_id", type: "integer" },
      { name: "occupancy_uuid", type: "string" },
      { name: "property", type: "string" },
      { name: "property_address", type: "string" },
      { name: "property_city", type: "string" },
      { name: "property_id", type: "integer" },
      { name: "property_name", type: "string" },
      { name: "property_state", type: "string" },
      { name: "property_street", type: "string" },
      { name: "property_street2", type: "string" },
      { name: "property_zip", type: "string" },
      { name: "sdr_echeck_eligibility", type: "boolean" },
      { name: "tenant_name", type: "string" },
      { name: "tenant_status", type: "string" },
      { name: "unit", type: "string" },
      { name: "unit_id", type: "integer" },
    ],
    filters: [
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
      { name: "as_of_date", type: "date" },
      { name: "include_voided", type: "boolean" },
    ],
  },
  {
    id: "tenant_directory",
    title: "Tenant Directory",
    summary: "All tenants with lease terms, contact detail, portal status, and fee settings.",
    tags: ["tenants"],
    verified: true,
    source: "live-verified against Perpetual Realty account, 2026-08-25",
    columns: [
      { name: "ais_enabled", type: "boolean" },
      { name: "auto_nsf_fee_amount", type: "number" },
      { name: "bed_name", type: "string" },
      { name: "certified_funds_only", type: "boolean" },
      { name: "commercial_lease_type", type: "string" },
      { name: "company_name", type: "string" },
      { name: "deposit", type: "number" },
      { name: "emails", type: "array" },
      { name: "first_name", type: "string" },
      { name: "guest_card_id", type: "integer" },
      { name: "ignore_partial_payments", type: "boolean" },
      { name: "inquiry_id", type: "integer" },
      { name: "insurance_company_name", type: "string" },
      { name: "insurance_expiration", type: "date" },
      { name: "insurance_policy_number", type: "string" },
      { name: "last_lease_renewal", type: "date" },
      { name: "last_name", type: "string" },
      { name: "last_rent_increase", type: "date" },
      { name: "late_fee_base_amount", type: "number" },
      { name: "late_fee_daily_amount", type: "number" },
      { name: "late_fee_grace_balance", type: "number" },
      { name: "late_fee_type", type: "string" },
      { name: "lease_from", type: "date" },
      { name: "lease_to", type: "date" },
      { name: "lease_uuid", type: "string" },
      { name: "license_plates", type: "array" },
      { name: "max_daily_late_fees_amount", type: "number" },
      { name: "move_in", type: "date" },
      { name: "move_out", type: "date" },
      { name: "next_rent_adjustment", type: "date" },
      { name: "next_rent_increase", type: "date" },
      { name: "occupancy_id", type: "integer" },
      { name: "occupancy_import_uid", type: "string" },
      { name: "occupancy_integration_id", type: "string" },
      { name: "online_payments_recurring_count", type: "integer" },
      { name: "online_payments_recurring_total", type: "number" },
      { name: "pets", type: "array" },
      { name: "phone_numbers", type: "array" },
      { name: "portfolio_id", type: "integer" },
      { name: "primary_tenant", type: "boolean" },
      { name: "property", type: "string" },
      { name: "property_address", type: "string" },
      { name: "property_city", type: "string" },
      { name: "property_id", type: "integer" },
      { name: "property_name", type: "string" },
      { name: "property_state", type: "string" },
      { name: "property_street", type: "string" },
      { name: "property_street2", type: "string" },
      { name: "property_zip", type: "string" },
      { name: "rent", type: "number" },
      { name: "rent_grace_day_fixed_day", type: "integer" },
      { name: "rent_grace_days", type: "integer" },
      { name: "rental_application_id", type: "integer" },
      { name: "require_online_payments_in_full", type: "boolean" },
      { name: "room_name", type: "string" },
      { name: "sdr_echeck_eligibility", type: "boolean" },
      { name: "selected_tenant_id", type: "integer" },
      { name: "send_rent_reminders", type: "boolean" },
      { name: "status", type: "string" },
      { name: "tenant", type: "string" },
      { name: "tenant_address", type: "string" },
      { name: "tenant_agent", type: "string" },
      { name: "tenant_birthdate", type: "date" },
      { name: "tenant_city", type: "string" },
      { name: "tenant_integration_id", type: "string" },
      { name: "tenant_notes", type: "string" },
      { name: "tenant_portal_activated", type: "boolean" },
      { name: "tenant_portal_login", type: "string" },
      { name: "tenant_sdr_payment", type: "boolean" },
      { name: "tenant_state", type: "string" },
      { name: "tenant_street", type: "string" },
      { name: "tenant_street2", type: "string" },
      { name: "tenant_tags", type: "array" },
      { name: "tenant_type", type: "string" },
      { name: "tenant_visibility", type: "string" },
      { name: "tenant_zip", type: "string" },
      { name: "transaction_fee", type: "number" },
      { name: "unit", type: "string" },
      { name: "unit_id", type: "integer" },
      { name: "unit_tags", type: "array" },
      { name: "unit_type", type: "string" },
    ],
    filters: [
      { name: "tenant_visibility", type: "string" },
      { name: "tenant_types", type: "array" },
      { name: "property_visibility", type: "string" },
      { name: "properties.properties_ids", type: "array" },
      { name: "properties.property_groups_ids", type: "array" },
      { name: "properties.portfolios_ids", type: "array" },
      { name: "properties.owners_ids", type: "array" },
    ],
  },
];
