// ABOUTME: Generated by scripts/generate-database-catalog.ts from AppFolio's OpenAPI HTML export.
// ABOUTME: Do not hand-edit, re-run the script against a fresh export instead.
import type { RawOperation } from "./catalogGen";

export const DATABASE_OPERATIONS: RawOperation[] = [
  {
    "method": "GET",
    "path": "/bank_accounts",
    "operationId": "getBankAccounts",
    "summary": "List All Bank Accounts",
    "tag": "Bank Accounts"
  },
  {
    "method": "POST",
    "path": "/bank_accounts/bulk",
    "operationId": "bulkCreateBankAccounts",
    "summary": "Bulk Create Bank Accounts",
    "tag": "Bank Accounts"
  },
  {
    "method": "POST",
    "path": "/bank_adjustments/bulk",
    "operationId": "bulkBankAdjustments",
    "summary": "Bulk Create Bank Adjustments",
    "tag": "Bank Adjustments"
  },
  {
    "method": "POST",
    "path": "/bank_statements/bulk",
    "operationId": "bulkCreateBankStatements",
    "summary": "Bulk Create Bank Statements",
    "tag": "Bank Statements"
  },
  {
    "method": "GET",
    "path": "/bills",
    "operationId": "getBills",
    "summary": "List All Bills",
    "tag": "Bills"
  },
  {
    "method": "POST",
    "path": "/bills",
    "operationId": "createBill",
    "summary": "Create Bill",
    "tag": "Bills"
  },
  {
    "method": "PATCH",
    "path": "/bills/{billId}",
    "operationId": "updateBill",
    "summary": "Update Bill",
    "tag": "Bills"
  },
  {
    "method": "POST",
    "path": "/bills/{BillId}/attachments",
    "operationId": "createBillAttachment",
    "summary": "Create Bill Attachment",
    "tag": "Bills"
  },
  {
    "method": "POST",
    "path": "/bills/bulk",
    "operationId": "bulkCreateBill",
    "summary": "Bulk Create Bills",
    "tag": "Bills"
  },
  {
    "method": "GET",
    "path": "/ca/bank_balances",
    "operationId": "getCaBankBalances",
    "summary": "List All Community Association Bank Account Balances",
    "tag": "Community Association Bank Balances"
  },
  {
    "method": "GET",
    "path": "/ca/board_members",
    "operationId": "getCaBoardMembers",
    "summary": "List All Community Association Board Members",
    "tag": "Community Association Board Members"
  },
  {
    "method": "GET",
    "path": "/ca/homeowners",
    "operationId": "getCaHomeowners",
    "summary": "List All Community Association Homeowners",
    "tag": "Community Association Homeowners"
  },
  {
    "method": "GET",
    "path": "/ca/homeowner_ledgers",
    "operationId": "getCaHomeownerLedgers",
    "summary": "List All Community Association Homeowner Ledgers",
    "tag": "Community Association Homeowner Ledgers"
  },
  {
    "method": "GET",
    "path": "/ca/renters",
    "operationId": "getCaRenters",
    "summary": "List All Community Association Renters",
    "tag": "Community Association Renters"
  },
  {
    "method": "GET",
    "path": "/ca/rules",
    "operationId": "getCaRules",
    "summary": "List All Community Association Rules",
    "tag": "Community Association Rules"
  },
  {
    "method": "GET",
    "path": "/ca/units",
    "operationId": "getCaUnits",
    "summary": "List All Community Association Units",
    "tag": "Community Association Units"
  },
  {
    "method": "GET",
    "path": "/ca/violations",
    "operationId": "getCaViolations",
    "summary": "List All Community Association Violations",
    "tag": "Community Association Violations"
  },
  {
    "method": "POST",
    "path": "/ca/violations",
    "operationId": "createCaViolation",
    "summary": "Create Community Association Violations ",
    "tag": "Community Association Violations"
  },
  {
    "method": "POST",
    "path": "/ca/violations/{violationId}/attachments",
    "operationId": "createCaViolationAttachment",
    "summary": "Create Community Association Violations Attachment",
    "tag": "Community Association Violations"
  },
  {
    "method": "PATCH",
    "path": "/ca/violations/{violationId}",
    "operationId": "updateCaViolation",
    "summary": "Update Community Association Violations",
    "tag": "Community Association Violations"
  },
  {
    "method": "GET",
    "path": "/charges",
    "operationId": "getCharges",
    "summary": "List All Charges",
    "tag": "Charges"
  },
  {
    "method": "POST",
    "path": "/charges",
    "operationId": "createCharge",
    "summary": "Create Charges",
    "tag": "Charges"
  },
  {
    "method": "POST",
    "path": "/charges/bulk",
    "operationId": "bulkCreateCharge",
    "summary": "Bulk Create Charges",
    "tag": "Charges"
  },
  {
    "method": "POST",
    "path": "/charges/{ChargeId}/attachments",
    "operationId": "createChargeAttachment",
    "summary": "Create Charge Attachment",
    "tag": "Charges"
  },
  {
    "method": "GET",
    "path": "/ca/associations",
    "operationId": "getCommunityAssociations",
    "summary": "List All Community Associations",
    "tag": "Community Associations"
  },
  {
    "method": "GET",
    "path": "/corporate_entities",
    "operationId": "getCorporateEntities",
    "summary": "List All Corporate Entities",
    "tag": "Corporate Entities"
  },
  {
    "method": "POST",
    "path": "/corporate/gl_accounts/bulk",
    "operationId": "bulkCreateCorporateGlAccounts",
    "summary": "Bulk Create Corporate General Ledger Accounts",
    "tag": "Corporate General Ledger Accounts"
  },
  {
    "method": "GET",
    "path": "/custom_fields",
    "operationId": "getCustomFields",
    "summary": "List All Custom Fields",
    "tag": "Custom Fields"
  },
  {
    "method": "GET",
    "path": "/delinquent_charges",
    "operationId": "getDelinquentCharges",
    "summary": "List All Delinquent Charges",
    "tag": "Delinquent Charges"
  },
  {
    "method": "GET",
    "path": "/gl_accounts",
    "operationId": "getGlAccounts",
    "summary": "List All General Ledger Accounts",
    "tag": "General Ledger Accounts"
  },
  {
    "method": "POST",
    "path": "/gl_accounts/bulk",
    "operationId": "bulkCreateGlAccounts",
    "summary": "Bulk Create General Ledger Accounts",
    "tag": "General Ledger Accounts"
  },
  {
    "method": "GET",
    "path": "/gl_details",
    "operationId": "getGlDetail",
    "summary": "List All General Ledger Details",
    "tag": "General Ledger Details"
  },
  {
    "method": "POST",
    "path": "/inspections/{InspectionId}/attachments",
    "operationId": "createInspectionAttachment",
    "summary": "Create Inspection Attachment",
    "tag": "Inspections"
  },
  {
    "method": "POST",
    "path": "/inspections",
    "operationId": "createInspection",
    "summary": "Create Inspection",
    "tag": "Inspections"
  },
  {
    "method": "POST",
    "path": "/inspections/bulk",
    "operationId": "bulkCreateInspections",
    "summary": "Bulk Create Inspections",
    "tag": "Inspections"
  },
  {
    "method": "PATCH",
    "path": "/inspections/{InspectionId}",
    "operationId": "updateInspection",
    "summary": "Update Inspection",
    "tag": "Inspections"
  },
  {
    "method": "DELETE",
    "path": "/inspections/{InspectionId}",
    "operationId": "deleteInspection",
    "summary": "Delete Inspection",
    "tag": "Inspections"
  },
  {
    "method": "GET",
    "path": "/inventory_locations",
    "operationId": "getInventoryLocations",
    "summary": "List All Inventory Locations",
    "tag": "Inventory Locations"
  },
  {
    "method": "GET",
    "path": "/jobs",
    "operationId": "getjobs",
    "summary": "List All Jobs",
    "tag": "Jobs"
  },
  {
    "method": "GET",
    "path": "/journal_entries",
    "operationId": "getJournalEntries",
    "summary": "List All Journal Entries",
    "tag": "Journal Entries"
  },
  {
    "method": "POST",
    "path": "/journal_entries",
    "operationId": "createJournalEntry",
    "summary": "Create Journal Entries",
    "tag": "Journal Entries"
  },
  {
    "method": "PATCH",
    "path": "/journal_entries/{JournalEntryId}",
    "operationId": "updateJournalEntry",
    "summary": "Update Journal Entries",
    "tag": "Journal Entries"
  },
  {
    "method": "POST",
    "path": "/journal_entries/bulk",
    "operationId": "bulkCreateJournalEntries",
    "summary": "Bulk Create Journal Entries",
    "tag": "Journal Entries"
  },
  {
    "method": "POST",
    "path": "/journal_entries/{JournalEntryId}/attachments",
    "operationId": "createJournalEntryAttachment",
    "summary": "Create Journal Entry Attachment",
    "tag": "Journal Entries"
  },
  {
    "method": "GET",
    "path": "/late_fee_policies",
    "operationId": "getLateFeePolicies",
    "summary": "List All Late Fee Policies",
    "tag": "Late Fee Policies"
  },
  {
    "method": "POST",
    "path": "/late_fee_policies/bulk",
    "operationId": "bulkCreateLateFeePolicies",
    "summary": "Bulk Create Late Fee Policies",
    "tag": "Late Fee Policies"
  },
  {
    "method": "GET",
    "path": "/leads",
    "operationId": "getLeads",
    "summary": "List All Leads",
    "tag": "Leads"
  },
  {
    "method": "POST",
    "path": "/leads",
    "operationId": "createLead",
    "summary": "Create Leads",
    "tag": "Leads"
  },
  {
    "method": "PATCH",
    "path": "/leads/{leadId}",
    "operationId": "updateLead",
    "summary": "Update Lead",
    "tag": "Leads"
  },
  {
    "method": "GET",
    "path": "/leads/notes",
    "operationId": "getLeadsNotes",
    "summary": "List All Leads Notes",
    "tag": "Leads"
  },
  {
    "method": "POST",
    "path": "/leads/{GuestCardId}/notes",
    "operationId": "createLeadNote",
    "summary": "Create Lead Note",
    "tag": "Leads"
  },
  {
    "method": "PATCH",
    "path": "/leads/{GuestCardId}/notes/{Id}",
    "operationId": "updateLeadNote",
    "summary": "Update Lead Note",
    "tag": "Leads"
  },
  {
    "method": "GET",
    "path": "/leases",
    "operationId": "getLeases",
    "summary": "List All Leases",
    "tag": "Leases"
  },
  {
    "method": "GET",
    "path": "/leases/renewal_pricings",
    "operationId": "getLeaseRenewalPricings",
    "summary": "List All Lease Renewal Pricings",
    "tag": "Leases"
  },
  {
    "method": "PUT",
    "path": "/leases/renewal_pricings/bulk",
    "operationId": "putBulkLeaseRenewalPricings",
    "summary": "Bulk Put Lease Renewal Pricings",
    "tag": "Leases"
  },
  {
    "method": "GET",
    "path": "/listings",
    "operationId": "getListings",
    "summary": "List All Listings",
    "tag": "Listings"
  },
  {
    "method": "GET",
    "path": "/mailing_letter",
    "operationId": "getMailingLetters",
    "summary": "List Mailing Letters",
    "tag": "Mailing Letters"
  },
  {
    "method": "PATCH",
    "path": "/mailing_letter/{mailingLetterId}",
    "operationId": "updateMailingLetter",
    "summary": "Update Mailing Letter",
    "tag": "Mailing Letters"
  },
  {
    "method": "PATCH",
    "path": "/mailing_letter/bulk_update",
    "operationId": "bulkUpdateMailingLetter",
    "summary": "Bulk Update Mailing Letters",
    "tag": "Mailing Letters"
  },
  {
    "method": "POST",
    "path": "/occupancies/{OccupancyId}/attachments",
    "operationId": "createOccupancyAttachment",
    "summary": "Create Occupancy Attachment",
    "tag": "Occupancies"
  },
  {
    "method": "GET",
    "path": "/occupancies/documents",
    "operationId": "getOccupancyDocuments",
    "summary": "List All Occupancies Documents",
    "tag": "Occupancies"
  },
  {
    "method": "GET",
    "path": "/owners",
    "operationId": "getOwners",
    "summary": "List All Owners",
    "tag": "Owners"
  },
  {
    "method": "POST",
    "path": "/owners",
    "operationId": "createOwner",
    "summary": "Create Owner",
    "tag": "Owners"
  },
  {
    "method": "GET",
    "path": "/owners/{ownerId}",
    "operationId": "getOwner",
    "summary": "Fetch an Owner by ID",
    "tag": "Owners"
  },
  {
    "method": "PATCH",
    "path": "/owners/{ownerId}",
    "operationId": "updateOwner",
    "summary": "Update Owner",
    "tag": "Owners"
  },
  {
    "method": "POST",
    "path": "/owners/bulk",
    "operationId": "bulkCreateOwners",
    "summary": "Bulk Create Owners",
    "tag": "Owners"
  },
  {
    "method": "POST",
    "path": "/owners/{OwnerId}/attachments",
    "operationId": "createOwnerAttachment",
    "summary": "Create Owner Attachment",
    "tag": "Owners"
  },
  {
    "method": "GET",
    "path": "/owners/attachments",
    "operationId": "listOwnerAttachments",
    "summary": "List All Owner Attachments",
    "tag": "Owners"
  },
  {
    "method": "GET",
    "path": "/owners/notes",
    "operationId": "getOwnersNotes",
    "summary": "List All Owners Notes",
    "tag": "Owners"
  },
  {
    "method": "POST",
    "path": "/owners/{OwnerId}/notes",
    "operationId": "createOwnerNote",
    "summary": "Create Owner Note",
    "tag": "Owners"
  },
  {
    "method": "PATCH",
    "path": "/owners/{OwnerId}/notes/{Id}",
    "operationId": "updateOwnerNote",
    "summary": "Update Owner Note",
    "tag": "Owners"
  },
  {
    "method": "GET",
    "path": "/owner_groups",
    "operationId": "getOwnerGroups",
    "summary": "List All Owner Groups",
    "tag": "Owner Groups"
  },
  {
    "method": "POST",
    "path": "/owner_groups",
    "operationId": "createOwnerGroup",
    "summary": "Create Owner Group",
    "tag": "Owner Groups"
  },
  {
    "method": "PATCH",
    "path": "/owner_groups/{id}",
    "operationId": "updateOwnerGroup",
    "summary": "Update Owner Group",
    "tag": "Owner Groups"
  },
  {
    "method": "GET",
    "path": "/payables",
    "operationId": "getPayables",
    "summary": "List All Payables",
    "tag": "Payables"
  },
  {
    "method": "POST",
    "path": "/prepayments/bulk",
    "operationId": "bulkCreatePrepayments",
    "summary": "Bulk Create Prepayments",
    "tag": "Prepayments"
  },
  {
    "method": "GET",
    "path": "/portfolios",
    "operationId": "getPortfolios",
    "summary": "List All Portfolios",
    "tag": "Portfolios"
  },
  {
    "method": "PATCH",
    "path": "/portfolios/{portfolioId}",
    "operationId": "updatePortfolio",
    "summary": "Update a Portfolio",
    "tag": "Portfolios"
  },
  {
    "method": "GET",
    "path": "/properties",
    "operationId": "getProperties",
    "summary": "List All Properties",
    "tag": "Properties"
  },
  {
    "method": "POST",
    "path": "/properties/bulk",
    "operationId": "bulkCreateProperties",
    "summary": "Bulk Create Properties",
    "tag": "Properties"
  },
  {
    "method": "PATCH",
    "path": "/properties/{propertyId}",
    "operationId": "updateProperty",
    "summary": "Update Property",
    "tag": "Properties"
  },
  {
    "method": "GET",
    "path": "/properties/attachments",
    "operationId": "listPropertyAttachments",
    "summary": "List All Property Attachments",
    "tag": "Properties"
  },
  {
    "method": "POST",
    "path": "/properties/{PropertyId}/attachments",
    "operationId": "createPropertyAttachment",
    "summary": "Create Property Attachment",
    "tag": "Properties"
  },
  {
    "method": "GET",
    "path": "/properties/notes",
    "operationId": "getPropertiesNotes",
    "summary": "List All Properties Notes",
    "tag": "Properties"
  },
  {
    "method": "POST",
    "path": "/properties/{PropertyId}/notes",
    "operationId": "createpropertyNote",
    "summary": "Create Property Note",
    "tag": "Properties"
  },
  {
    "method": "PATCH",
    "path": "/properties/{PropertyId}/notes/{Id}",
    "operationId": "updatepropertyNote",
    "summary": "Update Property Note",
    "tag": "Properties"
  },
  {
    "method": "GET",
    "path": "/properties/marketing_photos",
    "operationId": "getPropertiesMarketingPhotos",
    "summary": "List All Properties Marketing Photos",
    "tag": "Properties"
  },
  {
    "method": "PATCH",
    "path": "/properties/{PropertyId}/marketing_photos/{MarketingPhotoId}",
    "operationId": "updatePropertyMarketingPhoto",
    "summary": "Update Property Marketing Photo",
    "tag": "Properties"
  },
  {
    "method": "DELETE",
    "path": "/properties/{PropertyId}/marketing_photos/{MarketingPhotoId}",
    "operationId": "deletePropertyMarketingPhoto",
    "summary": "Delete Property Marketing Photo",
    "tag": "Properties"
  },
  {
    "method": "GET",
    "path": "/properties/photos",
    "operationId": "getPropertiesPhotos",
    "summary": "List All Properties Photos",
    "tag": "Properties"
  },
  {
    "method": "POST",
    "path": "/properties/{PropertyId}/marketing_photos",
    "operationId": "createPropertyMarketingPhoto",
    "summary": "Create Property Marketing Photo",
    "tag": "Properties"
  },
  {
    "method": "POST",
    "path": "/properties/{PropertyId}/photos",
    "operationId": "createPropertyPhoto",
    "summary": "Create Property Photo",
    "tag": "Properties"
  },
  {
    "method": "PATCH",
    "path": "/properties/{PropertyId}/photos/{PhotoId}",
    "operationId": "updatepropertyPhoto",
    "summary": "Update Property Photo",
    "tag": "Properties"
  },
  {
    "method": "DELETE",
    "path": "/properties/{PropertyId}/photos/{PhotoId}",
    "operationId": "deletePropertyPhoto",
    "summary": "Delete Property Photo",
    "tag": "Properties"
  },
  {
    "method": "GET",
    "path": "/property_groups",
    "operationId": "getPropertyGroups",
    "summary": "List All Property Groups",
    "tag": "Property Groups"
  },
  {
    "method": "PATCH",
    "path": "/property_groups/{propertyGroupId}",
    "operationId": "updatePropertyGroup",
    "summary": "Update a Property Group",
    "tag": "Property Groups"
  },
  {
    "method": "GET",
    "path": "/recurring_charges",
    "operationId": "getRecurringCharges",
    "summary": "List All Recurring Charges",
    "tag": "Recurring Charges"
  },
  {
    "method": "POST",
    "path": "/recurring_charges",
    "operationId": "createRecurringCharges",
    "summary": "Create Recurring Charges",
    "tag": "Recurring Charges"
  },
  {
    "method": "PATCH",
    "path": "/recurring_charges/{recurringChargeId}",
    "operationId": "updateRecurringCharge",
    "summary": "Update Recurring Charges",
    "tag": "Recurring Charges"
  },
  {
    "method": "POST",
    "path": "/rental_applications/{RentalApplicationId}/attachments",
    "operationId": "createRentalApplicationAttachment",
    "summary": "Create Rental Application Attachment",
    "tag": "Rental Applications"
  },
  {
    "method": "GET",
    "path": "/rental_applications",
    "operationId": "getRentalApplications",
    "summary": "List All Rental Applications",
    "tag": "Rental Applications"
  },
  {
    "method": "PATCH",
    "path": "/rental_applications/{rentalApplicationId}",
    "operationId": "updateRentalApplication",
    "summary": "Update Rental Application",
    "tag": "Rental Applications"
  },
  {
    "method": "GET",
    "path": "/rental_applications/notes",
    "operationId": "getRentalApplicationsNotes",
    "summary": "List All Rental Applications Notes",
    "tag": "Rental Applications"
  },
  {
    "method": "POST",
    "path": "/rental_applications/{RentalApplicationId}/notes",
    "operationId": "createRentalApplicationNote",
    "summary": "Create Rental Application Note",
    "tag": "Rental Applications"
  },
  {
    "method": "PATCH",
    "path": "/rental_applications/{RentalApplicationId}/notes/{Id}",
    "operationId": "updateRentalApplicationNote",
    "summary": "Update Rental Application Note",
    "tag": "Rental Applications"
  },
  {
    "method": "POST",
    "path": "/security_deposits/bulk",
    "operationId": "bulkCreateSecurityDeposits",
    "summary": "Bulk Create Security Deposits",
    "tag": "Security Deposits"
  },
  {
    "method": "GET",
    "path": "/showings",
    "operationId": "getShowings",
    "summary": "List All Showings",
    "tag": "Showings"
  },
  {
    "method": "POST",
    "path": "/showings",
    "operationId": "createShowing",
    "summary": "Create Showings",
    "tag": "Showings"
  },
  {
    "method": "PATCH",
    "path": "/showings/{showingId}",
    "operationId": "updateShowing",
    "summary": "Update Showing",
    "tag": "Showings"
  },
  {
    "method": "GET",
    "path": "/tenants",
    "operationId": "getTenants",
    "summary": "List All Tenants",
    "tag": "Tenants"
  },
  {
    "method": "PATCH",
    "path": "/tenants/{tenantId}",
    "operationId": "updateTenant",
    "summary": "Update Tenant",
    "tag": "Tenants"
  },
  {
    "method": "GET",
    "path": "/tenants/notes",
    "operationId": "getTenantsNotes",
    "summary": "List All Tenants Notes",
    "tag": "Tenants"
  },
  {
    "method": "POST",
    "path": "/tenants/{TenantId}/notes",
    "operationId": "createTenantNote",
    "summary": "Create Tenant Note",
    "tag": "Tenants"
  },
  {
    "method": "PATCH",
    "path": "/tenants/{TenantId}/notes/{Id}",
    "operationId": "updateTenantNote",
    "summary": "Update Tenant Note",
    "tag": "Tenants"
  },
  {
    "method": "POST",
    "path": "/tenants/bulk",
    "operationId": "bulkCreateTenants",
    "summary": "Bulk Create Tenants",
    "tag": "Tenants"
  },
  {
    "method": "PATCH",
    "path": "/tenants/bulk",
    "operationId": "bulkUpdateTenants",
    "summary": "Bulk Update Tenants",
    "tag": "Tenants"
  },
  {
    "method": "GET",
    "path": "/tenant_ledgers",
    "operationId": "getTenantLedgers",
    "summary": "List All Tenant Ledgers",
    "tag": "Tenant Ledgers"
  },
  {
    "method": "GET",
    "path": "/units",
    "operationId": "getUnits",
    "summary": "List All Units",
    "tag": "Units"
  },
  {
    "method": "POST",
    "path": "/units/bulk",
    "operationId": "bulkCreateUnits",
    "summary": "Bulk Create Units",
    "tag": "Units"
  },
  {
    "method": "PUT",
    "path": "/units/pricing_matrices/bulk",
    "operationId": "putBulkUnitPricingMatrix",
    "summary": "Bulk Put Unit Pricing Matrix",
    "tag": "Units"
  },
  {
    "method": "PUT",
    "path": "/units/pricing_matrices/bulk/async",
    "operationId": "putBulkUnitPricingMatrixAsync",
    "summary": "Bulk Put Unit Pricing Matrix (Async)",
    "tag": "Units"
  },
  {
    "method": "PATCH",
    "path": "/units/{unitId}",
    "operationId": "updateUnit",
    "summary": "Update Unit",
    "tag": "Units"
  },
  {
    "method": "PUT",
    "path": "/units/{UnitId}/pricing_matrices",
    "operationId": "putUnitPricingMatrix",
    "summary": "Put Unit Pricing Matrix",
    "tag": "Units"
  },
  {
    "method": "POST",
    "path": "/units/{UnitId}/attachments",
    "operationId": "createUnitAttachment",
    "summary": "Create Unit Attachment",
    "tag": "Units"
  },
  {
    "method": "GET",
    "path": "/units/attachments",
    "operationId": "listUnitAttachments",
    "summary": "List All Unit Attachments",
    "tag": "Units"
  },
  {
    "method": "GET",
    "path": "/units/notes",
    "operationId": "getUnitsNotes",
    "summary": "List All Units Notes",
    "tag": "Units"
  },
  {
    "method": "POST",
    "path": "/units/{UnitId}/notes",
    "operationId": "createUnitNote",
    "summary": "Create Unit Note",
    "tag": "Units"
  },
  {
    "method": "PATCH",
    "path": "/units/{UnitId}/notes/{Id}",
    "operationId": "updateUnitNote",
    "summary": "Update Unit Note",
    "tag": "Units"
  },
  {
    "method": "POST",
    "path": "/units/{UnitId}/photos",
    "operationId": "createUnitPhoto",
    "summary": "Create Unit Photo",
    "tag": "Units"
  },
  {
    "method": "PATCH",
    "path": "/units/{UnitId}/photos/{PhotoId}",
    "operationId": "updateUnitPhoto",
    "summary": "Update Unit Photo",
    "tag": "Units"
  },
  {
    "method": "DELETE",
    "path": "/units/{UnitId}/photos/{PhotoId}",
    "operationId": "deleteUnitPhoto",
    "summary": "Delete Unit Photo",
    "tag": "Units"
  },
  {
    "method": "GET",
    "path": "/units/photos",
    "operationId": "getUnitsPhotos",
    "summary": "List All Units Photos",
    "tag": "Units"
  },
  {
    "method": "GET",
    "path": "/unit_types",
    "operationId": "getUnitTypes",
    "summary": "List All Unit Types",
    "tag": "Unit Types"
  },
  {
    "method": "POST",
    "path": "/unit_types/bulk",
    "operationId": "bulkCreateUnitTypes",
    "summary": "Bulk Create Unit Types",
    "tag": "Unit Types"
  },
  {
    "method": "PATCH",
    "path": "/unit_types/{unitTypeId}",
    "operationId": "updateUnitType",
    "summary": "Update Unit Type",
    "tag": "Unit Types"
  },
  {
    "method": "GET",
    "path": "/users",
    "operationId": "getUsers",
    "summary": "List All Users",
    "tag": "Users"
  },
  {
    "method": "GET",
    "path": "/vendors",
    "operationId": "getVendors",
    "summary": "List All Vendors",
    "tag": "Vendors"
  },
  {
    "method": "POST",
    "path": "/vendors",
    "operationId": "createVendor",
    "summary": "Create Vendor",
    "tag": "Vendors"
  },
  {
    "method": "PATCH",
    "path": "/vendors/{vendorId}",
    "operationId": "updateVendor",
    "summary": "Update Vendor",
    "tag": "Vendors"
  },
  {
    "method": "POST",
    "path": "/vendors/bulk",
    "operationId": "bulkCreateVendors",
    "summary": "Bulk Create Vendors",
    "tag": "Vendors"
  },
  {
    "method": "GET",
    "path": "/vendors/notes",
    "operationId": "getVendorsNotes",
    "summary": "List All Vendors Notes",
    "tag": "Vendors"
  },
  {
    "method": "POST",
    "path": "/vendors/{VendorId}/notes",
    "operationId": "createVendorNote",
    "summary": "Create Vendor Note",
    "tag": "Vendors"
  },
  {
    "method": "PATCH",
    "path": "/vendors/{VendorId}/notes/{Id}",
    "operationId": "updateVendorNote",
    "summary": "Update Vendor Note",
    "tag": "Vendors"
  },
  {
    "method": "GET",
    "path": "/work_orders",
    "operationId": "getWorkOrders",
    "summary": "List All Work Orders",
    "tag": "Work Orders"
  },
  {
    "method": "POST",
    "path": "/work_orders",
    "operationId": "createWorkOrder",
    "summary": "Create Work Orders",
    "tag": "Work Orders"
  },
  {
    "method": "GET",
    "path": "/work_orders/attachments",
    "operationId": "listWorkOrderAttachments",
    "summary": "List All Work Order Attachments",
    "tag": "Work Orders"
  },
  {
    "method": "PATCH",
    "path": "/work_orders/{workOrderId}",
    "operationId": "updateWorkOrder",
    "summary": "Update Work Order",
    "tag": "Work Orders"
  },
  {
    "method": "POST",
    "path": "/work_orders/{WorkOrderId}/attachments",
    "operationId": "createWorkOrderAttachment",
    "summary": "Create Work Order Attachment",
    "tag": "Work Orders"
  },
  {
    "method": "DELETE",
    "path": "/work_orders/{WorkOrderId}/attachments/{AttachmentId}",
    "operationId": "deleteWorkOrderAttachment",
    "summary": "Delete Work Order Attachment",
    "tag": "Work Orders"
  },
  {
    "method": "POST",
    "path": "/work_orders/{WorkOrderId}/notes",
    "operationId": "createWorkOrderNote",
    "summary": "Create Work Order Note",
    "tag": "Work Orders"
  },
  {
    "method": "PATCH",
    "path": "/work_orders/{WorkOrderId}/notes/{Id}",
    "operationId": "updateWorkOrderNote",
    "summary": "Update Work Order Note",
    "tag": "Work Orders"
  }
];
