// ABOUTME: One-time/manual CLI: reads AppFolio's Redocly HTML export and writes the committed
// ABOUTME: operations.generated.ts data file plus a human-readable docs/reference/database-api.md mirror.
import { readFileSync, writeFileSync } from "node:fs";
import { basename } from "node:path";
import { extractReDocState, extractOperations, type RawOperation } from "../src/database/catalogGen";

const htmlPath = process.argv[2];
const outPath = process.argv[3] ?? "src/database/operations.generated.ts";
const docsPath = process.argv[4] ?? "docs/reference/database-api.md";
if (!htmlPath) {
  console.error("Usage: tsx scripts/generate-database-catalog.ts <path-to-html-export> [out-path] [docs-path]");
  process.exit(1);
}

const html = readFileSync(htmlPath, "utf8");
const state = extractReDocState(html);
const ops = extractOperations(state);
const baseUrl = state.spec?.data?.servers?.[0]?.url ?? "unknown";

const header = `// ABOUTME: Generated by scripts/generate-database-catalog.ts from AppFolio's OpenAPI HTML export.\n// ABOUTME: Do not hand-edit, re-run the script against a fresh export instead.\nimport type { RawOperation } from "./catalogGen";\n\nexport const DATABASE_OPERATIONS: RawOperation[] = `;
writeFileSync(outPath, header + JSON.stringify(ops, null, 2) + ";\n");
console.log(`Wrote ${ops.length} operations to ${outPath}`);

writeFileSync(docsPath, renderDocs(ops, basename(htmlPath), baseUrl));
console.log(`Wrote docs for ${ops.length} operations to ${docsPath}`);

function classify(op: RawOperation): "READ" | "WRITE" | "DESTRUCTIVE" {
  const isBulk = /bulk/i.test(op.operationId) || /bulk/i.test(op.path);
  if (op.method === "DELETE" || isBulk) return "DESTRUCTIVE";
  if (op.method === "GET") return "READ";
  return "WRITE";
}

function renderDocs(ops: RawOperation[], sourceFile: string, baseUrl: string): string {
  const byTag = new Map<string, RawOperation[]>();
  for (const op of ops) {
    const tagOps = byTag.get(op.tag) ?? [];
    tagOps.push(op);
    byTag.set(op.tag, tagOps);
  }
  const tags = [...byTag.keys()].sort((a, b) => a.localeCompare(b));

  const lines: string[] = [];
  lines.push("# AppFolio Database API Reference");
  lines.push("");
  lines.push(`Source: \`${sourceFile}\``);
  lines.push("");
  lines.push(`Base URL: \`${baseUrl}\``);
  lines.push("");
  lines.push(`Total operations: ${ops.length}`);
  lines.push("");
  lines.push(`Tags: ${tags.length}`);
  lines.push("");
  lines.push(
    "The Class column is a simple lightweight classification for readability only: READ for GET, DESTRUCTIVE for DELETE or any operation whose id/path matches \"bulk\", WRITE for everything else. It is not the role-scoping used elsewhere in this project.",
  );
  lines.push("");

  for (const tag of tags) {
    const tagOps = [...byTag.get(tag)!].sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method));
    lines.push(`## ${tag}`);
    lines.push("");
    lines.push("| Method | Path | Operation ID | Summary | Class |");
    lines.push("|---|---|---|---|---|");
    for (const op of tagOps) {
      lines.push(`| ${op.method} | \`${op.path}\` | \`${op.operationId}\` | ${op.summary} | ${classify(op)} |`);
    }
    lines.push("");
  }

  return lines.join("\n");
}
